#!/bin/sh
# This is a shell archive (produced by GNU sharutils 4.7).
# To extract the files from this archive, save it to some FILE, remove
# everything before the `#!/bin/sh' line above, then type `sh FILE'.
#
lock_dir=_sh26675
# Made on 2016-10-23 00:29 EDT by <n00886248@osprey.unfcsd.unf.edu>.
# Source directory was `/home/48/n00886248/Compilers/p'.
#
# Existing files will *not* be overwritten, unless `-c' is specified.
#
# This shar contains:
# length mode       name
# ------ ---------- ------------------------------------------
#     57 -rw-r--r-- makefile
#     28 -rwxr-xr-x p2
#   2584 -rw-r--r-- doc.txt
#    156 -rw-r--r-- test.txt
#      6 -rw-r--r-- sample.txt
#    994 -rw-r--r-- f2.py
#   2229 -rw-r--r-- findcmnts.py
#   3094 -rw-r--r-- lexical.py
#  19759 -rw-r--r-- parse.py
#    774 -rw-r--r-- queue.py
#
MD5SUM=${MD5SUM-md5sum}
f=`${MD5SUM} --version | egrep '^md5sum .*(core|text)utils'`
test -n "${f}" && md5check=true || md5check=false
${md5check} || \
  echo 'Note: not verifying md5sums.  Consider installing GNU coreutils.'
save_IFS="${IFS}"
IFS="${IFS}:"
gettext_dir=FAILED
locale_dir=FAILED
first_param="$1"
for dir in $PATH
do
  if test "$gettext_dir" = FAILED && test -f $dir/gettext \
     && ($dir/gettext --version >/dev/null 2>&1)
  then
    case `$dir/gettext --version 2>&1 | sed 1q` in
      *GNU*) gettext_dir=$dir ;;
    esac
  fi
  if test "$locale_dir" = FAILED && test -f $dir/shar \
     && ($dir/shar --print-text-domain-dir >/dev/null 2>&1)
  then
    locale_dir=`$dir/shar --print-text-domain-dir`
  fi
done
IFS="$save_IFS"
if test "$locale_dir" = FAILED || test "$gettext_dir" = FAILED
then
  echo=echo
else
  TEXTDOMAINDIR=$locale_dir
  export TEXTDOMAINDIR
  TEXTDOMAIN=sharutils
  export TEXTDOMAIN
  echo="$gettext_dir/gettext -s"
fi
if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null
then if (echo -n test; echo 1,2,3) | grep n >/dev/null
     then shar_n= shar_c='
'
     else shar_n=-n shar_c= ; fi
else shar_n= shar_c='\c' ; fi
f=shar-touch.$$
st1=200112312359.59
st2=123123592001.59
st2tr=123123592001.5 # old SysV 14-char limit
st3=1231235901

if touch -am -t ${st1} ${f} >/dev/null 2>&1 && \
   test ! -f ${st1} && test -f ${f}; then
  shar_touch='touch -am -t $1$2$3$4$5$6.$7 "$8"'

elif touch -am ${st2} ${f} >/dev/null 2>&1 && \
   test ! -f ${st2} && test ! -f ${st2tr} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$1$2.$7 "$8"'

elif touch -am ${st3} ${f} >/dev/null 2>&1 && \
   test ! -f ${st3} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$2 "$8"'

else
  shar_touch=:
  echo
  ${echo} 'WARNING: not restoring timestamps.  Consider getting and'
  ${echo} 'installing GNU `touch'\'', distributed in GNU coreutils...'
  echo
fi
rm -f ${st1} ${st2} ${st2tr} ${st3} ${f}
#
if test ! -d ${lock_dir}
then : ; else ${echo} 'lock directory '${lock_dir}' exists'
  exit 1
fi
if mkdir ${lock_dir}
then ${echo} 'x - created lock directory `'${lock_dir}\''.'
else ${echo} 'x - failed to create lock directory `'${lock_dir}\''.'
  exit 1
fi
# ============= makefile ==============
if test -f 'makefile' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING makefile (file already exists)'
else
${echo} 'x - extracting makefile (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'makefile' &&
all:
X	@echo " no make file neccesary, project in python"
SHAR_EOF
  (set 20 16 10 22 23 57 35 'makefile'; eval "$shar_touch") &&
  chmod 0644 'makefile'
if test $? -ne 0
then ${echo} 'restore of makefile failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'makefile: MD5 check failed'
       ) << \SHAR_EOF
c1bc7412f3c5bf3f05485f316ea63dbb  makefile
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'makefile'` -ne 57 && \
  ${echo} 'restoration warning:  size of makefile is not 57'
  fi
fi
# ============= p2 ==============
if test -f 'p2' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING p2 (file already exists)'
else
${echo} 'x - extracting p2 (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'p2' &&
#!/bin/bash
python f2.py $1
SHAR_EOF
  (set 20 16 10 22 23 56 16 'p2'; eval "$shar_touch") &&
  chmod 0755 'p2'
if test $? -ne 0
then ${echo} 'restore of p2 failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'p2: MD5 check failed'
       ) << \SHAR_EOF
5c47a4595ccd4a28b037b78a364de0bf  p2
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'p2'` -ne 28 && \
  ${echo} 'restoration warning:  size of p2 is not 28'
  fi
fi
# ============= doc.txt ==============
if test -f 'doc.txt' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING doc.txt (file already exists)'
else
${echo} 'x - extracting doc.txt (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 doc.txt
M*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ
M*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*@T*#0I.86UE.B!2
M86IA;B!086YD>6$@;C`P.#@V,C0X#0H-"@T*0VQA<W,Z($-/4#0V,C`@0T].
M4U1254-424].($]&($Q!3D=504=%(%1204Y33$%43U)3#0H-"E!R;VIE8W0@
M,B!3>6YT87@@06YA;'EZ97(-"@T*1FEL97,@26YC;'5D960Z#0H-"C$N(&8R
M+G!Y("AS;W5R8V4@9FEL92D-"C(N(&QE>&EC86PN<'D@*'-O=7)C92!F:6QE
M*0T*,RX@9FEN9&-M;G1S+G!Y("AS;W5R8V4@9FEL92D-"C(N(&UA:V5F:6QE
M#0HS+B!P,B`H=&\@<G5N('1H92!S;W5R8V4@9FEL92D-"C0N('1E<W0N='AT
M("AT97-T(&9I;&4I#0HU+B!D;V,N='AT("A$;V-U;65N=&%T:6]N(&9I;&4I
M(`T*-BX@<V%M<&QE+G1X="`H;W5T<'5T(&9I;&4@9F]R('1H92!G:79E;B!T
M97-T(&9I;&4I(`T*#0I(;W<@=&\@<G5N('1H92!0<F]G<F%M.@T*#0I4:&ES
M('!R;V=R86TL('-I;F-E('!Y=&AO;B!L86YG=6%G92!I<R!U<V5D+"!D;V5S
M(&YO="!N965D('1O(&5X96-U=&4@;6%K92!C;VUM86YD+@T*5&AI<R!P<F]G
M<F%M(&-A;B!B92!E>&5C=71E9"!B>2!T>7!I;F<@)RXO<#(@=&5S="<N(`T*
M26YS=&5A9"!O9B!M>2!T97-T(&9I;&4L('5S97)S(&-A;B!U<V4@=&AE:7(@
M;W=N('1E>'0@;W(@;&EN=7@@9FEL92!A<R!A;B!C;VUM86YD(&QI;F4@87)G
M=6UE;G0N#0H-"@T*1V5N97)A;"!$:7-C<FEP=&EO;CH-"@T*5&AE(&8R+G!Y
M(&%C8V5P=',@82!F:6QE(&9R;VT@8V]M;6%N9"!L:6YE+B`-"DET(')E8V]G
M;FEZ97,@:68@=&AE(&9I;&4@:7,@;F]T('!R;W9I9&5D(&EN(&-O;6UA;F0@
M;&EN92!A<F=U;65N=',L(&%N9"!P<FEN=',@82!M97-S86=E+@T*270@<W!L
M:71S('1H92!C;VYT96YT(&9R;VT@9VEV96X@9FEL92!I;G1O(&UA;GD@<V5N
M=&5N8V5S(&%N9"!S=&]R92!T:&5M(&EN(&%N(&%R<F%Y+B`-"D]N92`G9F]R
M(&QO;W`G(')U;G,@=&AR;W5G:"!T:&%T(&%R<F%Y+"!A;F0@8V%L;',@82!F
M=6YC=&EO;B!N86UE9"`G9FEN9&-M;G1S)R!A;F0@)VQE>&EC86PG('=I=&@@
M<&%S<VEN9R!O;F4@;&EN92!A="!A('1I;64N(`T*5&AE("=L97AI8V%L)R!U
M<V5S('1H92!S=')I;F<@=&AA="!I<R!R971U<FYE9"!B>2`G9FEN9&-M;G1S
M)R!F=6YC=&EO;BT@869T97(@<F5M;W9I;F<@8V]M;65N=',@:6YC;'5D:6YG
M(&YE<W1E9"!O;F5S+@T*26X@)V9I;F1C;6YT<R<L('1H97)E(&ES(&$@9VQO
M8F%L('9A<FEA8FQE(&YA;65D("=C;W5N=&5R)R!W:&EC:"!K965P<R!T<F%C
M:R!O9B!T:&4@;G5M8F5R(&]F(&UU;'1I;&EN92!C;VUM96YT<RX-"E5P;VX@
M<F5C96EV:6YG('-T<FEN9R!F<F]M("=F:6YD8VUN=',G+"!T:&4@)VQE>&EC
M86PG(&%P<&QI97,@9&EF9F5R96YT(')E9W5L87(@97AP<F5S<VEO;G,@;VX@
M=&AE('-T<FEN9RP@86YD(`T*"7-E<&5R871E<R!T:&5M(&EN=&\@=&]K96YS
M+"!A;F0@<')I;G1S('1H96TN#0H):2YE(&ED+"!N=6TL(&]P97)A=&]R<RP@
M<&%R96YT:&5S:7,L(&ME>7=O<F1S+"!E=&,N#0I4:&4@)VQE>&EC86PG('5S
M97,@=&AE(&9U;F-T:6]N("=F:6YD:V5Y<R<@=&\@<V5P97)A=&4@:V5Y=V]R
M9',@9G)O;2!I9',N(`T*270@8V%L;',@)V9I;F1K97ES)R!W:&5N979E<B!I
M="!F:6YD<R!A;B!I9"P@86YD("=F:6YD:V5Y<R<@9&5T97)M:6YE<R!A;F0@
M<')I;G1S(&EF(&ET(&ES(&%N(&ED(&]R(&$@:V5Y=V]R9"X-"D9U;F-T:6]N
M("=F:6YD:V5Y<R<@=7-E<R!A(&=L;V)A;"!V87)I86)L92`G:V5Y=V]R9',G
M('=H:6-H(&AA<R!A;&P@=&AE(&ME>7=O<F1S('-T;W)E9"!I;B!A;B!A<G)A
M>2X-"E1H92`G;&5X:6-A;"<@<F5C;V=N:7IE<R!A;&P@9&EF9F5R96YT('1O
M:V5N<R!A;F0@97)R;W(L(&EF(&%N>2P@86YD(&ET('!R:6YT<R!T:&5M(&]N
M92!B>2!O;F4@:6X@=&AE('-A;64@;W)D97(@=&AE>2!C86UE+@T*57!O;B!R
M96-E:79I;F<@=&]K96YS(&9R;VT@<')O:F5C="`Q+"!P87)S92YP>2!F:6QE
M(&=O97,@=&AR;W5G:"!G<F%M;6%R(')U;&5S(&]F($,M(&QA;F=U86=E('9I
M82!M971H;V1S(&EN(&-L87-S(%!A<G-I;F<N(`T*270@:&%S(&1I8W1I;VYA
M<FEE<R!T;R!H;VQD(&]N('1O('1H92!F:7)S=',@86YD(&9O;&QO=W,@;V8@
M=&AE(&=R86UM87(@<G5L92!N;VXM=&5R;6EN86QS+B`-"E1H92!P<F]G<F%M
M('5S97,@=&AE(&-U<G)E;G0@=&]K96XL(&9I<G-T<RP@86YD(&9O;&QO=W,@
M87,@82!P871H('1O('1R879E<G-E('1H<F]U9V@@;65T:&]D<R!I;B!T:&4@
M8VQA<W,N($ET(&AA<R!A;B!O8FIE8W0@<75E=64@;V8@8VQA<W,@475E=64@
M=&\@<W1O<F4@86QL('1H92!T;VME;G,@9G)O;2!P<F]J96-T(#$N(`T*3VYC
M92!T:&4@8W5R<F5N="!T;VME;B!I<R!O;B!F:7)S="!I;F1E>"!O9B!T:&4@
M<75E=64L(&%N9"!I="!I<R`D+"!!0T-%4%0@:7,@<')I;G1E9"X@3W1H97)W
M:7-E+"!214I%0U0@:7,@<')I;G1E9"X-"@T**BHJ*BHJ*BHJ*BHJ*BHJ*BHJ
M*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ
3*BHJ*BHJ*BHJ*BHJ*BHJ*BH-"BHJ
`
end
SHAR_EOF
  (set 20 16 10 23 00 28 28 'doc.txt'; eval "$shar_touch") &&
  chmod 0644 'doc.txt'
if test $? -ne 0
then ${echo} 'restore of doc.txt failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'doc.txt: MD5 check failed'
       ) << \SHAR_EOF
1891326ae13f0bd319030e3ed77f31e1  doc.txt
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'doc.txt'` -ne 2584 && \
  ${echo} 'restoration warning:  size of doc.txt is not 2584'
  fi
fi
# ============= test.txt ==============
if test -f 'test.txt' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING test.txt (file already exists)'
else
${echo} 'x - extracting test.txt (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 test.txt
M:6YT(&=C9"`H(&EN="!U("P@:6YT('8@*0T*>PDO+R!N;W1E('!R;V(@:&5R
M90T*"6EF("@@=B`]/2`P("D-"@D)<F5T=7)N('4@.PT*"65L<V4-"@D)<F5T
M=7)N(&=C9"`H('8@+"!U("T@=2`O('8@*B!V("D[#0H)+RH@;F]T92!U+2AU
5+W8J=BD@/2!U(&UO9"!V("HO#0I]
`
end
SHAR_EOF
  (set 20 16 10 22 23 53 28 'test.txt'; eval "$shar_touch") &&
  chmod 0644 'test.txt'
if test $? -ne 0
then ${echo} 'restore of test.txt failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'test.txt: MD5 check failed'
       ) << \SHAR_EOF
cfa78df32ca5a17c23f0ed0ae6dce5c8  test.txt
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'test.txt'` -ne 156 && \
  ${echo} 'restoration warning:  size of test.txt is not 156'
  fi
fi
# ============= sample.txt ==============
if test -f 'sample.txt' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING sample.txt (file already exists)'
else
${echo} 'x - extracting sample.txt (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 sample.txt
&04-#15!4
`
end
SHAR_EOF
  (set 20 16 10 23 00 28 59 'sample.txt'; eval "$shar_touch") &&
  chmod 0644 'sample.txt'
if test $? -ne 0
then ${echo} 'restore of sample.txt failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'sample.txt: MD5 check failed'
       ) << \SHAR_EOF
1fd72e016e8fbf2cf1f0c918dcd9bad3  sample.txt
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'sample.txt'` -ne 6 && \
  ${echo} 'restoration warning:  size of sample.txt is not 6'
  fi
fi
# ============= f2.py ==============
if test -f 'f2.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING f2.py (file already exists)'
else
${echo} 'x - extracting f2.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 f2.py
M(R$O8FEN+V)A<V@@<'ET:&]N#0II;7!O<G0@<WES#0II;7!O<G0@;&5X:6-A
M;`T*:6UP;W)T(&9I;F1C;6YT<PT*:6UP;W)T('%U975E#0II;7!O<G0@<&%R
M<V4-"@T*#0II9B!?7VYA;65?7R`]/2`G7U]M86EN7U\G.@T*("`@(&QI;F5S
M(#T@6UT-"B`@("!D(#T@>WT-"B`@("!Q(#T@<75E=64N475E=64H*0T*("`@
M('1R>3H-"B`@("`@("`@=VET:"!O<&5N*'-Y<RYA<F=V6S%=+"`G<B<I(&%S
M(&9I;&4Z#0H@("`@("`@("`@("!P87-S#0H@("`@("`@("`@("!F;W(@92!I
M;B!F:6QE.@T*("`@("`@("`@("`@("`@(&QI;F5S+F%P<&5N9"AE+G)S=')I
M<"@G7&XG*2D-"B`@("`@("`@("`@(&9I;&4N8VQO<V4H*0T*("`@(&5X8V5P
M=#H-"B`@("`@("`@<')I;G0@)U1H:7,@<')O9W)A;2!N965D<R!A(&9I;&4@
M87)G=6UE;G0N)PT*("`@(&EF(&QI;F5S.@T*("`@("`@("!F;W(@;&EN92!I
M;B!L:6YE<SH-"B`@("`@("`@("`@(&EF(&QE;BAL:6YE*2`^(#`Z#0H@("`@
M("`@("`@("`@("`@;&EN92`](&9I;F1C;6YT<RYF:6YD8VUN=',H;&EN92D-
M"B`@("`@("`@("`@("`@("!Q+"!E(#T@;&5X:6-A;"YL97AI8V%L*&QI;F4L
M('$L(&0I#0H@("`@("`@("`@("`@("`@9"YU<&1A=&4H92D-"B`@("`@("`@
M("`@("`@("`C(&EF(&YO="!Q+FES16UP='DH*3H-"B`@("`@("`@("`@("`@
M("`C("`@("!Q+G!R:6YT<2@I#0H@("`@("`@("`@("`@("`@(R!I9B!D.@T*
M("`@("`@("`@("`@("`@(",@("`@('!R:6YT(&0-"B`@("`@("`@:68@;F]T
M('$N:7-%;7!T>2@I(&%N9"!D.@T*("`@("`@("`@("`@<2YE;G%U975E*"<D
M)RD-"B`@("`@("`@("`@(&0N=7!D871E*'LG)"<Z("<D)WTI#0H@("`@("`@
M("`@("!P(#T@<&%R<V4N4&%R<VEN9RAQ+"!D*0T*("`@("`@("`@("`@:68@
M<"YS=&%R="@I.@T*("`@("`@("`@("`@("`@('!R:6YT)T%#0T505"<-"B`@
M("`@("`@("`@(&5L<V4Z#0H@("`@("`@("`@("`@("`@<')I;G0@)U)%2D5#
$5"<-"B`@
`
end
SHAR_EOF
  (set 20 16 10 23 00 24 59 'f2.py'; eval "$shar_touch") &&
  chmod 0644 'f2.py'
if test $? -ne 0
then ${echo} 'restore of f2.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'f2.py: MD5 check failed'
       ) << \SHAR_EOF
74a8801bec9871fd72ba87ecfe95af30  f2.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'f2.py'` -ne 994 && \
  ${echo} 'restoration warning:  size of f2.py is not 994'
  fi
fi
# ============= findcmnts.py ==============
if test -f 'findcmnts.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING findcmnts.py (file already exists)'
else
${echo} 'x - extracting findcmnts.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 findcmnts.py
M:6UP;W)T(')E#0H-"F-O=6YT97(@/2`P#0H-"@T*9&5F(&9I;F1C;6YT<RAL
M;&EN92DZ#0H@("`@(B(B#0H@("`@270@9FEN9',@86YD(')E;6]V97,@9&EF
M9F5R96YT('1Y<&5S(&]F(&-O;6UE;G1S(&9R;VT@=&AE(&=I=F5N('-T<FEN
M9RX-"B`@("`Z<&%R86T@;&QI;F4Z($ET(&ES(&$@9VEV96X@<W1R:6YG+@T*
M("`@(#IR971U<FXZ($ET(')E='5R;G,@=&AE('-T<FEN9R!A9G1E<B!S=')I
M<&EN9R!O9F8@8V]M;65N=',N#0H@("`@(B(B#0H@("`@9VQO8F%L(&-O=6YT
M97(-"B`@("!C;W5N=&5R,B`](&-O=6YT97(-"B`@("!P870S(#T@<F4N8V]M
M<&EL92@G*#\Z*%M<+UU;7"I=*7PH6UPJ75M<+UTI?"A;7"]=6UPO72DI)RD-
M"B`@("!M;&-S(#T@6UT-"B`@("!S;&,@/2!;70T*("`@(&UL8V4@/2!;70T*
M("`@(&EN9'AS(#T@6UT-"B`@("!B;"`]($9A;'-E#0H@("`@:70@/2!R92YF
M:6YD:71E<BAP870S+"!L;&EN92D-"B`@("!C:&%N9V4@/2!&86QS90T*("`@
M(&9O<B!M871C:"!I;B!I=#H-"B`@("`@("`@:68@;6%T8V@N9W)O=7`H*3H-
M"B`@("`@("`@("`@(&EN9'AS+F%P<&5N9"AM871C:"YS=&%R="@I*0T*("`@
M("`@("`@("`@:68@;6%T8V@N9W)O=7`H*2`]/2`G+RHG.@T*("`@("`@("`@
M("`@("`@(&UL8W,N87!P96YD*&UA=&-H+F=R;W5P*"DI#0H@("`@("`@("`@
M("`@("`@;6QC92YA<'!E;F0H)R<I#0H@("`@("`@("`@("`@("`@<VQC+F%P
M<&5N9"@G)RD-"B`@("`@("`@("`@("`@("!C;W5N=&5R("L](#$-"B`@("`@
M("`@("`@(&5L:68@;6%T8V@N9W)O=7`H*2`]/2`G*B\G.@T*("`@("`@("`@
M("`@("`@(&UL8W,N87!P96YD*"<G*0T*("`@("`@("`@("`@("`@(&UL8V4N
M87!P96YD*&UA=&-H+F=R;W5P*"DI#0H@("`@("`@("`@("`@("`@<VQC+F%P
M<&5N9"@G)RD-"B`@("`@("`@("`@("`@("!I9B!C;W5N=&5R(#X@,#H-"B`@
M("`@("`@("`@("`@("`@("`@8V]U;G1E<B`M/2`Q#0H@("`@("`@("`@("`@
M("`@("`@(&-H86YG92`](%1R=64-"B`@("`@("`@("`@(&5L<V4Z#0H@("`@
M("`@("`@("`@("`@;6QC<RYA<'!E;F0H)R<I#0H@("`@("`@("`@("`@("`@
M;6QC92YA<'!E;F0H)R<I#0H@("`@("`@("`@("`@("`@<VQC+F%P<&5N9"AM
M871C:"YG<F]U<"@I*0T*("`@("`@("`@("`@8FP@/2!4<G5E#0H@("`@;G=L
M:6YE(#T@)R<-"B`@("!O;F-E(#T@5')U90T*("`@(&EF(&YO="!B;#H-"B`@
M("`@("`@:68@8V]U;G1E<B`^(#`Z#0H@("`@("`@("`@("!R971U<FX@)R<-
M"B`@("`@("`@<F5T=7)N(&QL:6YE#0H@("`@96QI9B!L96XH:6YD>',I(#T]
M(#$@86YD(&UL8V5;,%T@86YD(&-O=6YT97(@/3T@,"!A;F0@;F]T(&-H86YG
M93H-"B`@("`@("`@<F5T=7)N(&QL:6YE#0H@("`@96QS93H-"B`@("`@("`@
M:2`](#`-"B`@("`@("`@9F]R(&EN9&5X(&EN(&EN9'AS.@T*("`@("`@("`@
M("`@:68@;6QC<UMI72!O<B!S;&-;:5TZ#0H@("`@("`@("`@("`@("`@:68@
M;VYC93H-"B`@("`@("`@("`@("`@("`@("`@;G=L:6YE("L](&QL:6YE6SII
M;F1E>%T-"B`@("`@("`@("`@("`@("`@("`@;VYC92`]($9A;'-E#0H@("`@
M("`@("`@("`@("`@:68@;6QC<SH-"B`@("`@("`@("`@("`@("`@("`@8V]U
M;G1E<C(@*ST@,0T*("`@("`@("`@("`@96QI9B!M;&-E6VE=.@T*("`@("`@
M("`@("`@("`@(&EF(&-O=6YT97(R(#T](#`Z#0H@("`@("`@("`@("`@("`@
M("`@(&EF(&D@*R`Q(#T](&QE;BAI;F1X<RDZ#0H@("`@("`@("`@("`@("`@
M("`@("`@("!N=VQI;F4@*ST@;&QI;F5;:6YD97@Z70T*("`@("`@("`@("`@
M("`@("`@("!E;'-E.@T*("`@("`@("`@("`@("`@("`@("`@("`@;G=L:6YE
M("L](&QL:6YE6VEN9&5X.FEN9'AS6VD@*R`Q75T-"B`@("`@("`@("`@("`@
M("!I9B!C;W5N=&5R,B`^(#`Z#0H@("`@("`@("`@("`@("`@("`@(&-O=6YT
M97(R("T](#$-"B`@("`@("`@("`@("`@("`@("`@:68@8V]U;G1E<C(@/3T@
M,#H-"B`@("`@("`@("`@("`@("`@("`@("`@(&EF(&D@*R`Q(#T](&QE;BAI
M;F1X<RDZ#0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@;G=L:6YE("L]
M(&QL:6YE6VEN9&5X("L@,CI=#0H@("`@("`@("`@("`@("`@("`@("`@("!E
M;'-E.@T*("`@("`@("`@("`@("`@("`@("`@("`@("`@(&YW;&EN92`K/2!L
M;&EN95MI;F1E>"`K(#(Z:6YD>'-;:2`K(#%=70T*("`@("`@("`@("`@:2`K
8/2`Q#0H@("`@<F5T=7)N(&YW;&EN90T*
`
end
SHAR_EOF
  (set 20 16 10 20 19 36 32 'findcmnts.py'; eval "$shar_touch") &&
  chmod 0644 'findcmnts.py'
if test $? -ne 0
then ${echo} 'restore of findcmnts.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'findcmnts.py: MD5 check failed'
       ) << \SHAR_EOF
644a4b9af6b22ba682be6fa8fbf2df3b  findcmnts.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'findcmnts.py'` -ne 2229 && \
  ${echo} 'restoration warning:  size of findcmnts.py is not 2229'
  fi
fi
# ============= lexical.py ==============
if test -f 'lexical.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING lexical.py (file already exists)'
else
${echo} 'x - extracting lexical.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 lexical.py
M:6UP;W)T(')E#0H-"FME>7=O<F1S(#T@6R=E;'-E)RP@)VEF)RP@)W=H:6QE
M)RP@)W)E='5R;B<L("=I;G0G+"`G9FQO870G+"`G=F]I9"==#0H-"@T*9&5F
M(&QE>&EC86PH;&QI;F4L('$L(&0I.@T*("`@("(B(DET('-E<&%R871E<R!A
M;F0@<')I;G1S(&$@<W1R:6YG(&EN=&\@:61S+"!K97EW;W)D<RP@;G5M8F5R
M<RP@86YD(&UA;GD@9&EF9F5R96YT('1O:V5N<RX-"B`@("!!<F=S.@T*("`@
M("`@("!L;&EN93H@270@:7,@82!I;G!U="!S=')I;F<N#0H@("`@("`@('$Z
M($ET(&ES(&%N(&]B:F5C="!O9B!C;&%S<R!1=65U90T*("`@(%)E='5R;G,Z
M#0H@("`@("`@($YO=&AI;F<-"B`@("`B(B(-"B`@("!I9B!L96XH;&QI;F4I
M(#X@,#H-"B`@("`@("`@(R!D97-C(#T@6R=E<G)O<CHG+`T*("`@("`@("`C
M("`@("`@("`@)V9L;V%T.B<L("=F;&]A=#HG+`T*("`@("`@("`C("`@("`@
M("`@)VYU;3HG+"`G;G5M.B<L#0H@("`@("`@(",@("`@("`@("`G9FQO870Z
M)RP@)V9L;V%T.B<L#0H@("`@("`@(",@("`@("`@("`G;G5M.B<L("=N=6TZ
M)RP-"B`@("`@("`@(R`@("`@("`@("=E<G)O<B<L("=E<G)O<CHG+"`G;W`Z
M)RP@)V]P.B<L("=E<G)O<B<L("<G+"`G;W`Z)RP@)R==#0H@("`@("`@(&1E
M<V,@/2!;)V5R<F]R)RP-"B`@("`@("`@("`@("`@("`G;G5M)RP@)VYU;2<L
M#0H@("`@("`@("`@("`@("`@)VYU;2<L("=N=6TG+`T*("`@("`@("`@("`@
M("`@("=N=6TG+"`G;G5M)RP-"B`@("`@("`@("`@("`@("`G;G5M)RP@)VYU
M;2<L#0H@("`@("`@("`@("`@("`@)V5R<F]R)RP@)V5R<F]R)RP@)V]P)RP@
M)V]P)RP@)V5R<F]R)RP@)R<L("=O<"<L("<G70T*("`@("`@("!I(#T@,`T*
M("`@("`@("!P870R(#T@<F4N8V]M<&EL92@G)R<H/SHH*#\\/5M!+41&+5IA
M+61F+7I=*5M>02U:82UZ7"%</%P^7%M<75Q[7'U<*%PI7#U<*UPM7"Q<.UPJ
M7"]<<UU;7EQS72HI?"`C(#$-"B`@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@*"@_/#U;7'-<*UPM7"I<+UP]72E;7&1=*UM<+EU;7&1=*RA;165=6UPK
M7"U<9%U;7&1=*BD_*7P@(R`R("8@,PT*("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`H*#\\/5M<<UPK7"U<*EPO7#U=*5M<9%TK*%M%95U;7"M<+5QD
M75M<9%TJ*3\I?"`C(#0@)B`U#0H@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@("A;7&1=*UM<+EU;7&1=*RA;165=6UPK7"U<9%U;7&1=*BD_*7P@(R`V
M("8@-PT*("`@("`@("`@("`@("`@("`@("`@("`@("`@("`H6UQD72LH6T5E
M75M<*UPM7&1=6UQD72HI/RE\(",@."`F(#D-"B`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@*"@_/"%<9"E;7"Y=/UM<9%TJ6T5E75LK+5T_6UQD72LI
M?"`C,3`-"B`@("`@("`@("`@("`@("`@("`@("`@("`@("`@*"@_/#U<9"E;
M7C`M.45E7"Y<<UP[7"Q<*5PH7%U<6UQ[7'U<*EPK7"U<+UU;7EP[7"Q<*5PH
M7%U<6UQ[7'U=*BE\(",Q,0T*("`@("`@("`@("`@("`@("`@("`@("`@("`@
M("`H6UP\7#Y<*UPM7"I<+UP]72E\(",@,3(-"B`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@*%M</%P^7"M<+5PJ7"]</5PA75M</5TI?"`C,3,-"B`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@*%M<(5PN72E\(",Q-`T*("`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`H6UPL7#M=*7P@(R`Q-0T*("`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`H6UQ;7%U<>UQ]7"A<*5TI?"`C
M(#$V#0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@("A;02U:82UZ72LI
M*2<G)RP@<F4N6"D@(",@,3<-"B`@("`@("`@:70@/2!R92YF:6YD86QL*'!A
M=#(L(&QL:6YE*0T*("`@("`@("!F;W(@;6%T8V@@:6X@:70Z#0H@("`@("`@
M("`@("!N(#T@,`T*("`@("`@("`@("`@9F]R(&D@:6X@;6%T8V@Z#0H@("`@
M("`@("`@("`@("`@:68@:3H-"B`@("`@("`@("`@("`@("`@("`@:68@;B`]
M/2`Q-CH-"B`@("`@("`@("`@("`@("`@("`@("`@(&4@/2!F:6YD:V5Y<RAI
M+"!Q+"!D*0T*("`@("`@("`@("`@("`@("`@("`@("`@9"YU<&1A=&4H92D-
M"B`@("`@("`@("`@("`@("`@("`@96QS93H-"B`@("`@("`@("`@("`@("`@
M("`@("`@(&EF(#`@/"!N(#P@.3H-"B`@("`@("`@("`@("`@("`@("`@("`@
M("`@("!Q+F5N<75E=64H:2D-"B`@("`@("`@("`@("`@("`@("`@("`@("`@
M("!D+G5P9&%T92A[:3H@9&5S8UMN77TI#0H@("`@("`@("`@("`@("`@("`@
M("`@("!E;&EF(&X@/3T@,3(Z#0H@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@<2YE;G%U975E*&E;,%TI#0H@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@<2YE;G%U975E*&E;,5TI#0H@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@9"YU<&1A=&4H>VE;,%TZ(&E;,%U]*0T*("`@("`@("`@("`@("`@("`@
M("`@("`@("`@(&0N=7!D871E*'MI6S%=.B!I6S%=?2D-"B`@("`@("`@("`@
M("`@("`@("`@("`@(&5L<V4Z#0H@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@<2YE;G%U975E*&DI#0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@
M9"YU<&1A=&4H>VDZ(&E]*0T*("`@("`@("`@("`@("`@("`@("!B<F5A:PT*
M("`@("`@("`@("`@("`@(&X@*ST@,0T*("`@(&5L<V4Z#0H@("`@("`@('!R
M:6YT("<G#0H@("`@<F5T=7)N('$L(&0-"@T*#0ID968@9FEN9&ME>7,H:6YP
M+"!Q+"!D*3H-"B`@("`B(B)$971E<FUI;F5S(&%N9"!P<FEN=',@=VAE=&AE
M<B!T:&4@9VEV96X@=V]R9"!I<R!A(&ME>7=O<F0@;W(@86X@:60N#0H@("`@
M07)G<SH-"B`@("`@("`@:6YP.B!)="!T86ME<R!A('-T<FEN9R!A<R!A;B!A
M<F=U;65N="X-"B`@("`@("`@<3H@270@:7,@86X@;V)J96-T(&]F(&-L87-S
M(%%U975E#0H@("`@("`@(&0Z($ET(&ES(&$@9&EC=&EO;F%R>0T*("`@(%)E
M='5R;G,Z#0H@("`@("`@($YO=&AI;F<-"B`@("`B(B(-"B`@("!G;&]B86P@
M:V5Y=V]R9',-"B`@("!I9B!I;G`@:6X@:V5Y=V]R9',Z#0H@("`@("`@('$N
M96YQ=65U92AI;G`I#0H@("`@("`@(&0N=7!D871E*'MI;G`Z(&EN<'TI#0H@
M("`@96QS93H-"B`@("`@("`@<2YE;G%U975E*&EN<"D-"B`@("`@("`@9"YU
B<&1A=&4H>VEN<#H@(FED(GTI#0H@("`@<F5T=7)N(&0-"B`@
`
end
SHAR_EOF
  (set 20 16 10 23 00 23 23 'lexical.py'; eval "$shar_touch") &&
  chmod 0644 'lexical.py'
if test $? -ne 0
then ${echo} 'restore of lexical.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'lexical.py: MD5 check failed'
       ) << \SHAR_EOF
e97b5539527f141fe89797d651dcc055  lexical.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'lexical.py'` -ne 3094 && \
  ${echo} 'restoration warning:  size of lexical.py is not 3094'
  fi
fi
# ============= parse.py ==============
if test -f 'parse.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING parse.py (file already exists)'
else
${echo} 'x - extracting parse.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 parse.py
M9&5F(&5X:71P9VTH*3H-"B`@("!P<FEN="`G4D5*14-4)PT*("`@(&5X:70H
M*0T*#0H-"F-L87-S(%!A<G-I;F<H;V)J96-T*3H-"B`@("!D968@7U]I;FET
M7U\H<V5L9BP@<2P@9"DZ#0H@("`@("`@('-E;&8N<2`]('$-"B`@("`@("`@
M<V5L9BYD(#T@9`T*("`@("`@("!S96QF+F9O;&QO=W,@/2![)W!G;2<Z(%LG
M)"==+`T*("`@("`@("`@("`@("`@("`@("`@("`@)V0M;&ES="<Z(%LG)"==
M+`T*("`@("`@("`@("`@("`@("`@("`@("`@)T$G.B!;)R0G72P-"B`@("`@
M("`@("`@("`@("`@("`@("`@("=D8VQA<G1N)SH@6R=I;G0G+"`G=F]I9"<L
M("=F;&]A="<L("<D)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G0B<Z
M(%LG:6YT)RP@)W9O:60G+"`G9FQO870G+"`G)"==+`T*("`@("`@("`@("`@
M("`@("`@("`@("`@)W9A<BUD8VQA<G1N)SH@6R<[)RP@)ULG+"`G:6YT)RP@
M)W9O:60G+"`G9FQO870G+"`G)"<L("=I9"<L("<H)RP@)VYU;2<L("=W:&EL
M92<L("=[)RP@)VEF)RP@)W)E='5R;B==+`T*("`@("`@("`@("`@("`@("`@
M("`@("`@)V9U;BUD8VQA<G1N)SH@6R=I;G0G+"`G=F]I9"<L("=F;&]A="<L
M("<D)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G='EP92US<&5C9G(G
M.B!;)VED)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G<&%R86US)SH@
M6R<I)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G<&%R86TM;&ES="<Z
M(%LG*2==+`T*("`@("`@("`@("`@("`@("`@("`@("`@)T0G.B!;)RDG72P-
M"B`@("`@("`@("`@("`@("`@("`@("`@("=P87)A;2<Z(%LG+"<L("<I)UTL
M#0H@("`@("`@("`@("`@("`@("`@("`@("`G12<Z(%LG+"<L("<I)UTL#0H@
M("`@("`@("`@("`@("`@("`@("`@("`G8V]M<&YD+7-T;70G.B!;)V5L<V4G
M+"`G.R<L("=I9"<L("<H)RP@)VYU;2<L("=W:&EL92<L("=[)RP@)VEF)RP@
M)W)E='5R;B<L("=I;G0G+"`G=F]I9"<L("=F;&]A="<L("<D)RP@)WTG72P-
M"B`@("`@("`@("`@("`@("`@("`@("`@("=L;V-A;"UD8VQA<G1N)SH@6R<[
M)RP@)VED)RP@)R@G+"`G;G5M)RP@)W=H:6QE)RP@)WLG+"`G:68G+"`G<F5T
M=7)N)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G1B<Z(%LG.R<L("=I
M9"<L("<H)RP@)VYU;2<L("=W:&EL92<L("=[)RP@)VEF)RP@)W)E='5R;B==
M+`T*("`@("`@("`@("`@("`@("`@("`@("`@)W-T871M;G0M;&ES="<Z(%LG
M?2==+`T*("`@("`@("`@("`@("`@("`@("`@("`@)T<G.B!;)WTG72P-"B`@
M("`@("`@("`@("`@("`@("`@("`@("=S=&%T;6YT)SH@6R=E;'-E)RP@)SLG
M+"`G:60G+"`G*"<L("=N=6TG+"`G=VAI;&4G+"`G>R<L("=I9B<L("=R971U
M<FXG+"`G?2==+`T*("`@("`@("`@("`@("`@("`@("`@("`@)V5X<')S;BUS
M=&UT)SH@6R=E;'-E)RP@)SLG+"`G:60G+"`G*"<L("=N=6TG+"`G=VAI;&4G
M+"`G>R<L("=I9B<L("=R971U<FXG+"`G?2==+`T*("`@("`@("`@("`@("`@
M("`@("`@("`@)W-E;&-T;BUS=&UT)SH@6R=E;'-E)RP@)SLG+"`G:60G+"`G
M*"<L("=N=6TG+"`G=VAI;&4G+"`G>R<L("=I9B<L("=R971U<FXG+"`G?2==
M+`T*("`@("`@("`@("`@("`@("`@("`@("`@)T@G.B!;)V5L<V4G+"`G.R<L
M("=I9"<L("<H)RP@)VYU;2<L("=W:&EL92<L("=[)RP@)VEF)RP@)W)E='5R
M;B<L("=])UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G:71E<G1N+7-T
M;70G.B!;)V5L<V4G+"`G.R<L("=I9"<L("<H)RP@)VYU;2<L("=W:&EL92<L
M("=[)RP@)VEF)RP@)W)E='5R;B<L("=])UTL#0H@("`@("`@("`@("`@("`@
M("`@("`@("`G<F5T<FXM<W1M="<Z(%LG96QS92<L("<[)RP@)VED)RP@)R@G
M+"`G;G5M)RP@)W=H:6QE)RP@)WLG+"`G:68G+"`G<F5T=7)N)RP@)WTG72P-
M"B`@("`@("`@("`@("`@("`@("`@("`@("=E>'!R<VXG.B!;)RPG+"`G*2<L
M("==)RP@)SLG72P-"B`@("`@("`@("`@("`@("`@("`@("`@("=3)SH@6R<L
M)RP@)RDG+"`G72<L("<[)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G
M5"<Z(%LG*R<L("<M)RP@)SPG+"`G/B<L("<])RP@)R$G+"`G*B<L("<O)RP@
M)RPG+"`G*2<L("==)RP@)SLG72P-"B`@("`@("`@("`@("`@("`@("`@("`@
M("=))SH@6R<L)RP@)RDG+"`G72<L("<[)UTL#0H@("`@("`@("`@("`@("`@
M("`@("`@("`G4"<Z(%LG+"<L("<I)RP@)UTG+"`G.R==+`T*("`@("`@("`@
M("`@("`@("`@("`@("`@)U$G.B!;)RLG+"`G+2<L("<\)RP@)SXG+"`G/2<L
M("<A)RP@)RHG+"`G+R<L("<L)RP@)RDG+"`G72<L("<[)UTL#0H@("`@("`@
M("`@("`@("`@("`@("`@("`G4B<Z(%LG+"<L("<I)RP@)UTG+"`G.R==+`T*
M("`@("`@("`@("`@("`@("`@("`@("`@)THG.B!;)STG+"`G*B<L("<O)RP@
M)RLG+"`G+2<L("<\)RP@)SXG+"`G(2<L("<L)RP@)RDG+"`G72<L("<[)UTL
M#0H@("`@("`@("`@("`@("`@("`@("`@("`G2R<Z(%LG+"<L("<I)RP@)UTG
M+"`G.R==+`T*("`@("`@("`@("`@("`@("`@("`@("`@)W)E;&]P)SH@6R<H
M)RP@)VED)RP@)VYU;2==+`T*("`@("`@("`@("`@("`@("`@("`@("`@)TPG
M.B!;)R@G+"`G:60G+"`G;G5M)UTL#0H@("`@("`@("`@("`@("`@("`@("`@
M("`G861D+65X<')S;B<Z(%LG/"<L("<^)RP@)STG+"`G(2<L("<L)RP@)RDG
M+"`G72<L("<[)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G32<Z(%LG
M/"<L("<^)RP@)STG+"`G(2<L("<L)RP@)RDG+"`G72<L("<[)UTL#0H@("`@
M("`@("`@("`@("`@("`@("`@("`G861D;W`G.B!;)R@G+"`G:60G+"`G;G5M
M)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G=&5R;2<Z(%LG*R<L("<M
M)RP@)SPG+"`G/B<L("<])RP@)R$G+"`G+"<L("<I)RP@)UTG+"`G.R==+`T*
M("`@("`@("`@("`@("`@("`@("`@("`@)TXG.B!;)RLG+"`G+2<L("<\)RP@
M)SXG+"`G/2<L("<A)RP@)RPG+"`G*2<L("==)RP@)SLG72P-"B`@("`@("`@
M("`@("`@("`@("`@("`@("=M=6QO<"<Z(%LG*"<L("=I9"<L("=N=6TG72P-
M"B`@("`@("`@("`@("`@("`@("`@("`@("=F86-T;W(G.B!;)RHG+"`G+R<L
M("<K)RP@)RTG+"`G/"<L("<^)RP@)STG+"`G(2<L("<L)RP@)RDG+"`G72<L
M("<[)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("`G=F%R8V%L;"<Z(%LG
M*B<L("<O)RP@)RLG+"`G+2<L("<\)RP@)SXG+"`G/2<L("<A)RP@)RPG+"`G
M*2<L("==)RP@)SLG72P-"B`@("`@("`@("`@("`@("`@("`@("`@("=C86QL
M)SH@6R<J)RP@)R\G+"`G*R<L("<M)RP@)SPG+"`G/B<L("<])RP@)R$G+"`G
M+"<L("<I)RP@)UTG+"`G.R==+`T*("`@("`@("`@("`@("`@("`@("`@("`@
M)V%R9W,G.B!;)RDG72P-"B`@("`@("`@("`@("`@("`@("`@("`@("=A<F<M
M;&ES="<Z(%LG*2==+`T*("`@("`@("`@("`@("`@("`@("`@("`@)T\G.B!;
M)RDG77T-"B`@("`@("`@<V5L9BYF:7)S=',@/2![)W!G;2<Z(%LG:6YT)RP@
M)W9O:60G+"`G9FQO870G72P-"B`@("`@("`@("`@("`@("`@("`@("`@)V0M
M;&ES="<Z(%LG:6YT)RP@)W9O:60G+"`G9FQO870G72P-"B`@("`@("`@("`@
M("`@("`@("`@("`@)T$G.B!;)R<L("=I;G0G+"`G=F]I9"<L("=F;&]A="==
M+`T*("`@("`@("`@("`@("`@("`@("`@("`G9&-L87)T;B<Z(%LG:6YT)RP@
M)W9O:60G+"`G9FQO870G72P-"B`@("`@("`@("`@("`@("`@("`@("`@)T(G
M.B!;)SLG+"`G6R<L("<H)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("=V
M87(M9&-L87)T;B<Z(%LG.R<L("=;)UTL#0H@("`@("`@("`@("`@("`@("`@
M("`@("=F=6XM9&-L87)T;B<Z(%LG*"==+`T*("`@("`@("`@("`@("`@("`@
M("`@("`G='EP92US<&5C9G(G.B!;)VEN="<L("=V;VED)RP@)V9L;V%T)UTL
M#0H@("`@("`@("`@("`@("`@("`@("`@("=P87)A;7,G.B!;)W9O:60G+"`G
M:6YT)RP@)V9L;V%T)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("=P87)A
M;2UL:7-T)SH@6R=I;G0G+"`G=F]I9"<L("=F;&]A="==+`T*("`@("`@("`@
M("`@("`@("`@("`@("`G1"<Z(%LG+"<L("<G72P-"B`@("`@("`@("`@("`@
M("`@("`@("`@)W!A<F%M)SH@6R=I;G0G+"`G=F]I9"<L("=F;&]A="==+`T*
M("`@("`@("`@("`@("`@("`@("`@("`G12<Z(%LG6R<L("<G72P-"B`@("`@
M("`@("`@("`@("`@("`@("`@)V-O;7!N9"US=&UT)SH@6R=[)UTL#0H@("`@
M("`@("`@("`@("`@("`@("`@("=L;V-A;"UD8VQA<G1N)SH@6R<G+"`G.R<L
M("=;)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("=&)SH@6R<G+"`G.R<L
M("=;)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("=S=&%T;6YT+6QI<W0G
M.B!;)R<L("<[)RP@)VED)RP@)R@G+"`G;G5M)RP@)W=H:6QE)RP@)WLG+"`G
M:68G+"`G<F5T=7)N)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("=')SH@
M6R<G+"`G.R<L("=I9"<L("<H)RP@)VYU;2<L("=W:&EL92<L("=[)RP@)VEF
M)RP@)W)E='5R;B==+`T*("`@("`@("`@("`@("`@("`@("`@("`G<W1A=&UN
M="<Z(%LG.R<L("=I9"<L("<H)RP@)VYU;2<L("=W:&EL92<L("=[)RP@)VEF
M)RP@)W)E='5R;B==+`T*("`@("`@("`@("`@("`@("`@("`@("`G97AP<G-N
M+7-T;70G.B!;)SLG+"`G:60G+"`G*"<L("=N=6TG72P-"B`@("`@("`@("`@
M("`@("`@("`@("`@)W-E;&-T;BUS=&UT)SH@6R=I9B==+`T*("`@("`@("`@
M("`@("`@("`@("`@("`G2"<Z(%LG96QS92<L("<G72P-"B`@("`@("`@("`@
M("`@("`@("`@("`@)VET97)T;BUS=&UT)SH@6R=W:&EL92==+`T*("`@("`@
M("`@("`@("`@("`@("`@("`G<F5T<FXM<W1M="<Z(%LG<F5T=7)N)UTL#0H@
M("`@("`@("`@("`@("`@("`@("`@("=E>'!R<VXG.B!;)VED)RP@)R@G+"`G
M;G5M)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("=3)SH@6R<H)RP@)VYU
M;2==+`T*("`@("`@("`@("`@("`@("`@("`@("`G5"<Z(%LG*"<L("=N=6TG
M72P-"B`@("`@("`@("`@("`@("`@("`@("`@)TDG.B!;)ULG+"`G)RP@)SPG
M+"`G/B<L("<])RP@)R$G+"`G*"<L("=N=6TG+"`G*B<L("<O)RP@)RLG+"`G
M+2==+`T*("`@("`@("`@("`@("`@("`@("`@("`G4"<Z(%LG*"<L("=;)RP@
M)VYU;2<L("<G+"`G*B<L("<O)RP@)SPG+"`G/B<L("<])RP@)R$G+"`G*R<L
M("<M)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("=1)SH@6R<H)RP@)ULG
M+"`G;G5M)RP@)R==+`T*("`@("`@("`@("`@("`@("`@("`@("`G4B<Z(%LG
M6R<L("<G+"`G/"<L("<^)RP@)STG+"`G(2==+`T*("`@("`@("`@("`@("`@
M("`@("`@("`G=F%R)SH@6R=I9"==+`T*("`@("`@("`@("`@("`@("`@("`@
M("`G2B<Z(%LG6R<L("<G72P-"B`@("`@("`@("`@("`@("`@("`@("`@)W-I
M;7!L92UE>'!R<VXG.B!;)R@G+"`G:60G+"`G;G5M)UTL#0H@("`@("`@("`@
M("`@("`@("`@("`@("=+)SH@6R<G+"`G/"<L("<^)RP@)STG+"`G(2==+`T*
M("`@("`@("`@("`@("`@("`@("`@("`G<F5L;W`G.B!;)SPG+"`G/B<L("<]
M)RP@)R$G72P-"B`@("`@("`@("`@("`@("`@("`@("`@)TPG.B!;)STG+"`G
M)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("=A9&0M97AP<G-N)SH@6R<H
M)RP@)VED)RP@)VYU;2==+`T*("`@("`@("`@("`@("`@("`@("`@("`G32<Z
M(%LG)RP@)RLG+"`G+2==+`T*("`@("`@("`@("`@("`@("`@("`@("`G861D
M;W`G.B!;)RLG+"`G+2==+`T*("`@("`@("`@("`@("`@("`@("`@("`G=&5R
M;2<Z(%LG*"<L("=I9"<L("=N=6TG72P-"B`@("`@("`@("`@("`@("`@("`@
M("`@)TXG.B!;)R<L("<J)RP@)R\G72P-"B`@("`@("`@("`@("`@("`@("`@
M("`@)VUU;&]P)SH@6R<J)RP@)R\G72P-"B`@("`@("`@("`@("`@("`@("`@
M("`@)V9A8W1O<B<Z(%LG*"<L("=I9"<L("=N=6TG72P-"B`@("`@("`@("`@
M("`@("`@("`@("`@)W9A<F-A;&PG.B!;)ULG+"`G)RP@)R@G72P-"B`@("`@
M("`@("`@("`@("`@("`@("`@)V-A;&PG.B!;)R@G72P-"B`@("`@("`@("`@
M("`@("`@("`@("`@)V%R9W,G.B!;)R<L("<H)RP@)VYU;2<L("=I9"==+`T*
M("`@("`@("`@("`@("`@("`@("`@("`G87)G+6QI<W0G.B!;)R@G+"`G;G5M
M)RP@)VED)UTL#0H@("`@("`@("`@("`@("`@("`@("`@("=/)SH@6R<L)RP@
M)R==?0T*("`@("`@("!S96QF+FD@/2!S96QF+G$N<VEZ92@I#0H@("`@("`@
M('-E;&8N=&5R;7,@/2!;)VED)RP@)SLG+"`G6R<L("=N=6TG+"`G72<L("<H
M)RP@)RDG+"`G:6YT)RP@)W9O:60G+"`G9FQO870G+"`G+"<L("=[)RP@)WTG
M+"`G:68G+"`G96QS92<L#0H@("`@("`@("`@("`@("`@("`@("`@)W=H:6QE
M)RP@)W)E='5R;B<L("<])RP@)SPG+"`G/B<L("<A)RP@)RLG+"`G+2<L("<J
M)RP@)R\G70T*#0H@("`@9&5F('-T87)T*'-E;&8I.@T*("`@("`@("!R971U
M<FX@<V5L9BYP9VTH<V5L9BYQ+G-I>F4H*2D-"@T*("`@(&1E9B!G971F:7)S
M="AS96QF+"!N;VYT97)M*3H-"B`@("`@("`@<F5T=7)N('-E;&8N9FER<W1S
M6VYO;G1E<FU=#0H-"B`@("!D968@9V5T9F]L;&]W*'-E;&8L(&YO;G1E<FTI
M.@T*("`@("`@("!R971U<FX@<V5L9BYF;VQL;W=S6VYO;G1E<FU=#0H-"B`@
M("!D968@;G0H<V5L9BP@;BDZ#0H@("`@("`@(&=E=&ED(#T@<V5L9BYQ+FEN
M9&5X960H;BD-"B`@("`@("`@<F5T=7)N('-E;&8N9%MG971I9%T-"@T*("`@
M(&1E9B!A8V-E<'0H<V5L9BP@<RP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H
M82D@:6X@<SH-"B`@("`@("`@("`@(`T*("`@("`@("`@("`@<F5T=7)N(&$M
M,0T*("`@("`@("!E;'-E.@T*("`@("`@("`@("`@97AI='!G;2@I#0H-"B`@
M("!D968@<&=M*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(#T]
M("<D)SH-"B`@("`@("`@("`@(')E='5R;B!4<G5E#0H@("`@("`@(&5L<V4Z
M#0H@("`@("`@("`@("!B(#T@<V5L9BYD7VQI<W0H82D-"B`@("`@("`@("`@
M(&EF(&(@/3T@,3H-"B`@("`@("`@("`@("`@("!R971U<FX@5')U90T*("`@
M("`@("`@("`@96QS93H-"B`@("`@("`@("`@("`@("!E>&ET<&=M*"D-"@T*
M("`@(&1E9B!D7VQI<W0H<V5L9BP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H
M82D@:6X@<V5L9BYG971F:7)S="@G9&-L87)T;B<I.@T*("`@("`@("`@("`@
M8B`]('-E;&8N9&-L87)T;BAA*0T*("`@("`@("`@("`@<F5T=7)N('-E;&8N
M02AB*0T*("`@("`@("!E;'-E.@T*("`@("`@("`@("`@97AI='!G;2@I#0H-
M"B`@("!D968@02AS96QF+"!A*3H-"B`@("`@("`@:68@<V5L9BYN="AA*2!I
M;B!S96QF+F=E=&9O;&QO=R@G02<I.@T*("`@("`@("`@("`@<F5T=7)N(&$-
M"B`@("`@("`@96QI9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9FER<W0H)V1C
M;&%R=&XG*3H-"B`@("`@("`@("`@(&(@/2!S96QF+F1C;&%R=&XH82D-"B`@
M("`@("`@("`@(')E='5R;B!S96QF+D$H8BD-"B`@("`@("`@96QS93H-"B`@
M("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F(&1C;&%R=&XH<V5L9BP@
M82DZ#0H@("`@("`@(&EF('-E;&8N;G0H82D@/3T@)W9O:60G.@T*("`@("`@
M("`@("`@8B`]('-E;&8N86-C97!T*"=V;VED)RP@82D-"B`@("`@("`@("`@
M(&,@/2!S96QF+F%C8V5P="@G:60G+"!B*0T*("`@("`@("`@("`@<F5T=7)N
M('-E;&8N9G5N7V1C;&%R=&XH8RD-"B`@("`@("`@96QI9B!S96QF+FYT*&$I
M(&EN('-E;&8N9V5T9FER<W0H)W1Y<&4M<W!E8V9R)RDZ#0H@("`@("`@("`@
M("!B(#T@<V5L9BYT>7!E7W-P96-F<BAA*0T*("`@("`@("`@("`@8R`]('-E
M;&8N86-C97!T*"=I9"<L(&(I#0H@("`@("`@("`@("!R971U<FX@<V5L9BY"
M*&,I#0H@("`@("`@(&5L<V4Z#0H@("`@("`@("`@("!E>&ET<&=M*"D-"@T*
M("`@(&1E9B!"*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(&EN
M('-E;&8N9V5T9FER<W0H)W9A<BUD8VQA<G1N)RDZ#0H@("`@("`@("`@("!R
M971U<FX@<V5L9BYV87)?9&-L87)T;BAA*0T*("`@("`@("!E;&EF('-E;&8N
M;G0H82D@:6X@<V5L9BYG971F:7)S="@G9G5N+61C;&%R=&XG*3H-"B`@("`@
M("`@("`@(')E='5R;B!S96QF+F9U;E]D8VQA<G1N*&$I#0H@("`@("`@(&5L
M<V4Z#0H@("`@("`@("`@("!E>&ET<&=M*"D-"@T*("`@(&1E9B!T>7!E7W-P
M96-F<BAS96QF+"!A*3H-"B`@("`@("`@:68@<V5L9BYN="AA*2`]/2`G:6YT
M)SH-"B`@("`@("`@("`@(')E='5R;B!S96QF+F%C8V5P="@G:6YT)RP@82D-
M"B`@("`@("`@96QI9B!S96QF+FYT*&$I(#T]("=F;&]A="<Z#0H@("`@("`@
M("`@("!R971U<FX@<V5L9BYA8V-E<'0H)V9L;V%T)RP@82D-"B`@("`@("`@
M96QI9B!S96QF+FYT*&$I(#T]("=V;VED)SH-"B`@("`@("`@("`@(')E='5R
M;B!S96QF+F%C8V5P="@G=F]I9"<L(&$I#0H@("`@("`@(&5L<V4Z#0H@("`@
M("`@("`@("!E>&ET<&=M*"D-"@T*("`@(&1E9B!V87)?9&-L87)T;BAS96QF
M+"!A*3H-"B`@("`@("`@:68@<V5L9BYN="AA*2`]/2`G.R<Z#0H@("`@("`@
M("`@("!R971U<FX@<V5L9BYA8V-E<'0H)SLG+"!A*0T*("`@("`@("!E;&EF
M('-E;&8N;G0H82D@/3T@)ULG.@T*("`@("`@("`@("`@8B`]('-E;&8N86-C
M97!T*"=;)RP@82D-"B`@("`@("`@("`@(&,@/2!S96QF+F%C8V5P="@G;G5M
M)RP@8BD-"B`@("`@("`@("`@(&0@/2!S96QF+F%C8V5P="@G72<L(&,I#0H@
M("`@("`@("`@("!R971U<FX@<V5L9BYA8V-E<'0H)SLG+"!D*0T*("`@("`@
M("!E;'-E.@T*("`@("`@("`@("`@97AI='!G;2@I#0H-"B`@("!D968@9G5N
M7V1C;&%R=&XH<V5L9BP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@
M6R<H)UTZ#0H@("`@("`@("`@("!B(#T@<V5L9BYA8V-E<'0H)R@G+"!A*0T*
M("`@("`@("`@("`@8R`]('-E;&8N<&%R86US*&(I#0H@("`@("`@("`@("!D
M(#T@<V5L9BYA8V-E<'0H)RDG+"!C*0T*("`@("`@("`@("`@<F5T=7)N('-E
M;&8N8V]M<&YD7W-T;70H9"D-"B`@("`@("`@96QS93H-"B`@("`@("`@("`@
M(&5X:71P9VTH*0T*#0H@("`@9&5F('!A<F%M<RAS96QF+"!A*3H-"B`@("`@
M("`@:68@<V5L9BYN="AA*2`]/2`G=F]I9"<Z#0H@("`@("`@("`@("!R971U
M<FX@<V5L9BYA8V-E<'0H)W9O:60G+"!A*0T*("`@("`@("!E;&EF('-E;&8N
M;G0H82D@:6X@<V5L9BYG971F:7)S="@G<&%R86TM;&ES="<I.@T*("`@("`@
M("`@("`@<F5T=7)N('-E;&8N<&%R86U?;&ES="AA*0T*("`@("`@("!E;'-E
M.@T*("`@("`@("`@("`@97AI='!G;2@I#0H-"B`@("!D968@<&%R86U?;&ES
M="AS96QF+"!A*3H-"B`@("`@("`@:68@<V5L9BYN="AA*2!I;B!S96QF+F=E
M=&9I<G-T*"=P87)A;2<I.@T*("`@("`@("`@("`@8B`]('-E;&8N<&%R86TH
M82D-"B`@("`@("`@("`@(')E='5R;B!S96QF+D0H8BD-"B`@("`@("`@96QS
M93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F($0H<V5L9BP@
M82DZ#0H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@6R<L)UTZ#0H@("`@("`@
M("`@("!B(#T@<V5L9BYA8V-E<'0H)RPG+"!A*0T*("`@("`@("`@("`@8R`]
M('-E;&8N<&%R86TH8BD-"B`@("`@("`@("`@(&0@/2!S96QF+D0H8RD-"B`@
M("`@("`@("`@(')E='5R;B!D#0H@("`@("`@(&5L:68@<V5L9BYN="AA*2!I
M;B!S96QF+F=E=&9O;&QO=R@G1"<I.@T*("`@("`@("`@("`@<F5T=7)N(&$-
M"B`@("`@("`@96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@
M9&5F('!A<F%M*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(&EN
M('-E;&8N9V5T9FER<W0H)W1Y<&4M<W!E8V9R)RDZ#0H@("`@("`@("`@("!B
M(#T@<V5L9BYT>7!E7W-P96-F<BAA*0T*("`@("`@("`@("`@8R`]('-E;&8N
M86-C97!T*"=I9"<L(&(I#0H@("`@("`@("`@("!R971U<FX@<V5L9BY%*&,I
M#0H@("`@("`@(&5L<V4Z#0H@("`@("`@("`@("!E>&ET<&=M*"D-"@T*("`@
M(&1E9B!%*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(&EN(%LG
M6R==.@T*("`@("`@("`@("`@8B`]('-E;&8N86-C97!T*"=;)RP@82D-"B`@
M("`@("`@("`@(')E='5R;B!S96QF+F%C8V5P="@G72<L(&(I#0H@("`@("`@
M(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9O;&QO=R@G12<I.@T*("`@
M("`@("`@("`@<F5T=7)N(&$-"B`@("`@("`@96QS93H-"B`@("`@("`@("`@
M(&5X:71P9VTH*0T*#0H@("`@9&5F(&-O;7!N9%]S=&UT*'-E;&8L(&$I.@T*
M("`@("`@("!I9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9FER<W0H)V-O;7!N
M9"US=&UT)RDZ#0H@("`@("`@("`@("!B(#T@<V5L9BYA8V-E<'0H)WLG+"!A
M*0T*("`@("`@("`@("`@8R`]('-E;&8N;&]C86Q?9&-L87)T;BAB*0T*("`@
M("`@("`@("`@9"`]('-E;&8N<W1A=&UN=%]L:7-T*&,I#0H@("`@("`@("`@
M("!R971U<FX@<V5L9BYA8V-E<'0H)WTG+"!D*0T*("`@("`@("!E;'-E.@T*
M("`@("`@("`@("`@97AI='!G;2@I#0H-"B`@("!D968@;&]C86Q?9&-L87)T
M;BAS96QF+"!A*3H-"B`@("`@("`@<F5T=7)N('-E;&8N1BAA*0T*#0H@("`@
M9&5F($8H<V5L9BP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@6R=I
M;G0G+"`G9FQO870G73H-"B`@("`@("`@("`@(&(@/2!S96QF+G1Y<&5?<W!E
M8V9R*&$I#0H@("`@("`@("`@("!C(#T@<V5L9BYA8V-E<'0H)VED)RP@8BD-
M"B`@("`@("`@("`@(&0@/2!S96QF+G9A<E]D8VQA<G1N*&,I#0H@("`@("`@
M("`@("!R971U<FX@<V5L9BY&*&0I#0H@("`@("`@(&5L:68@<V5L9BYN="AA
M*2!I;B!S96QF+F=E=&9O;&QO=R@G1B<I.@T*("`@("`@("`@("`@<F5T=7)N
M(&$-"B`@("`@("`@96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@
M("`@9&5F('-T871M;G1?;&ES="AS96QF+"!A*3H-"B`@("`@("`@<F5T=7)N
M('-E;&8N1RAA*0T*#0H@("`@9&5F($<H<V5L9BP@82DZ#0H@("`@("`@(&EF
M('-E;&8N;G0H82D@:6X@<V5L9BYG971F:7)S="@G<W1A=&UN="<I.@T*("`@
M("`@("`@("`@8B`]('-E;&8N<W1A=&UN="AA*0T*("`@("`@("`@("`@<F5T
M=7)N('-E;&8N1RAB*0T*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@<V5L
M9BYG971F;VQL;W<H)T<G*3H-"B`@("`@("`@("`@(')E='5R;B!A#0H@("`@
M("`@(&5L<V4Z#0H@("`@("`@("`@("!E>&ET<&=M*"D-"@T*("`@(&1E9B!S
M=&%T;6YT*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(&EN('-E
M;&8N9V5T9FER<W0H)V5X<')S;BUS=&UT)RDZ#0H@("`@("`@("`@("!R971U
M<FX@<V5L9BYE>'!R<VY?<W1M="AA*0T*("`@("`@("!E;&EF('-E;&8N;G0H
M82D@:6X@<V5L9BYG971F:7)S="@G<V5L8W1N+7-T;70G*3H-"B`@("`@("`@
M("`@(')E='5R;B!S96QF+G-E;&-T;E]S=&UT*&$I#0H@("`@("`@(&5L:68@
M<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=I=&5R=&XM<W1M="<I.@T*
M("`@("`@("`@("`@<F5T=7)N('-E;&8N:71E<G1N7W-T;70H82D-"B`@("`@
M("`@96QI9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9FER<W0H)W)E=')N+7-T
M;70G*3H-"B`@("`@("`@("`@(')E='5R;B!S96QF+G)E=')N7W-T;70H82D-
M"B`@("`@("`@96QI9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9FER<W0H)V-O
M;7!N9"US=&UT)RDZ#0H@("`@("`@("`@("!R971U<FX@<V5L9BYC;VUP;F1?
M<W1M="AA*0T*("`@("`@("!E;'-E.@T*("`@("`@("`@("`@97AI='!G;2@I
M#0H-"B`@("!D968@97AP<G-N7W-T;70H<V5L9BP@82DZ#0H@("`@("`@(&EF
M('-E;&8N;G0H82D@/3T@)SLG.@T*("`@("`@("`@("`@<F5T=7)N('-E;&8N
M86-C97!T*"<[)RP@82D-"B`@("`@("`@96QI9B!S96QF+FYT*&$I(&EN('-E
M;&8N9V5T9FER<W0H)V5X<')S;B<I.@T*("`@("`@("`@("`@8B`]('-E;&8N
M97AP<G-N*&$I#0H@("`@("`@("`@("!R971U<FX@<V5L9BYA8V-E<'0H)SLG
M+"!B*0T*("`@("`@("!E;'-E.@T*("`@("`@("`@("`@97AI='!G;2@I#0H-
M"B`@("!D968@<V5L8W1N7W-T;70H<V5L9BP@82DZ#0H@("`@("`@(&EF('-E
M;&8N;G0H82D@/3T@)VEF)SH-"B`@("`@("`@("`@(&(@/2!S96QF+F%C8V5P
M="@G:68G+"!A*0T*("`@("`@("`@("`@8R`]('-E;&8N86-C97!T*"<H)RP@
M8BD-"B`@("`@("`@("`@(&0@/2!S96QF+F5X<')S;BAC*0T*("`@("`@("`@
M("`@92`]('-E;&8N86-C97!T*"<I)RP@9"D-"B`@("`@("`@("`@(&8@/2!S
M96QF+G-T871M;G0H92D-"B`@("`@("`@("`@(')E='5R;B!S96QF+D@H9BD-
M"B`@("`@("`@96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@
M9&5F($@H<V5L9BP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H82D@/3T@)V5L
M<V4G.@T*("`@("`@("`@("`@8B`]('-E;&8N86-C97!T*"=E;'-E)RP@82D-
M"B`@("`@("`@("`@(')E='5R;B!S96QF+G-T871M;G0H8BD-"B`@("`@("`@
M96QI9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9F]L;&]W*"=()RDZ#0H@("`@
M("`@("`@("!R971U<FX@80T*("`@("`@("!E;'-E.@T*("`@("`@("`@("`@
M97AI='!G;2@I#0H-"B`@("!D968@:71E<G1N7W-T;70H<V5L9BP@82DZ#0H@
M("`@("`@(&EF('-E;&8N;G0H82D@/3T@)W=H:6QE)SH-"B`@("`@("`@("`@
M(&(@/2!S96QF+F%C8V5P="@G=VAI;&4G+"!A*0T*("`@("`@("`@("`@8R`]
M('-E;&8N86-C97!T*"<H)RP@8BD-"B`@("`@("`@("`@(&0@/2!S96QF+F5X
M<')S;BAC*0T*("`@("`@("`@("`@92`]('-E;&8N86-C97!T*"<I)RP@9"D-
M"B`@("`@("`@("`@(')E='5R;B!S96QF+G-T871M;G0H92D-"B`@("`@("`@
M96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F(')E=')N
M7W-T;70H<V5L9BP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H82D@/3T@)W)E
M='5R;B<Z#0H@("`@("`@("`@("!B(#T@<V5L9BYA8V-E<'0H)W)E='5R;B<L
M(&$I#0H@("`@("`@("`@("!R971U<FX@<V5L9BYE>'!R<VY?<W1M="AB*0T*
M("`@("`@("!E;'-E.@T*("`@("`@("`@("`@97AI='!G;2@I#0H-"B`@("`C
M(&1E9B!E>'!R<VXH<V5L9BP@82DZ#0H@("`@(R`@("`@:68@<V5L9BYM>6YT
M*&$I(&EN('-E;&8N9V5T9FER<W0H)W9A<B<I.@T*("`@(",@("`@("`@("!B
M(#T@<V5L9BYV87(H82D-"B`@("`C("`@("`@("`@8R`]('-E;&8N<F5L;W`H
M8BD-"B`@("`C("`@("`@("`@9"`]('-E;&8N97AP<G-N*&,I#0H@("`@(R`@
M("`@("`@(')E='5R;B!D#0H@("`@(R`@("`@96QI9B!S96QF+FUY;G0H82D@
M:6X@<V5L9BYG971F:7)S="@G<VEM<&QE+65X<')S;B<I.@T*("`@(",@("`@
M("`@("!R971U<FX@<V5L9BYS:6UP;&5?97AP<G-N*&$I#0H@("`@(R`@("`@
M96QS93H-"B`@("`C("`@("`@("`@97AI='!G;2@I#0H-"B`@("!D968@97AP
M<G-N*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(&EN(%LG:60G
M73H-"B`@("`@("`@("`@(&(@/2!S96QF+F%C8V5P="@G:60G+"!A*0T*("`@
M("`@("`@("`@<F5T=7)N('-E;&8N22AB*0T*("`@("`@("!E;&EF('-E;&8N
M;G0H82D@:6X@<V5L9BYG971F:7)S="@G4R<I.@T*("`@("`@("`@("`@<F5T
M=7)N('-E;&8N4RAA*0T*("`@("`@("!E;'-E.@T*("`@("`@("`@("`@97AI
M='!G;2@I#0H-"B`@("!D968@4RAS96QF+"!A*3H-"B`@("`@("`@:68@<V5L
M9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=3)RDZ#0H@("`@("`@("`@("!B
M(#T@<V5L9BY4*&$I#0H@("`@("`@("`@("!C(#T@<V5L9BY.*&(I#0H@("`@
M("`@("`@("!D(#T@<V5L9BY-*&,I#0H@("`@("`@("`@("!R971U<FX@<V5L
M9BY+*&0I#0H@("`@("`@(&5L<V4Z#0H@("`@("`@("`@("!E>&ET<&=M*"D-
M"@T*("`@(&1E9B!4*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I
M(#T]("<H)SH-"B`@("`@("`@("`@(&(@/2!S96QF+F%C8V5P="@G*"<L(&$I
M#0H@("`@("`@("`@("!C(#T@<V5L9BYE>'!R<VXH8BD-"B`@("`@("`@("`@
M(')E='5R;B!S96QF+F%C8V5P="@G*2<L(&,I#0H@("`@("`@(&5L:68@<V5L
M9BYN="AA*2`]/2`G;G5M)SH-"B`@("`@("`@("`@(')E='5R;B!S96QF+F%C
M8V5P="@G;G5M)RP@82D-"B`@("`@("`@96QS93H-"B`@("`@("`@("`@(&5X
M:71P9VTH*0T*#0H@("`@9&5F($DH<V5L9BP@82DZ#0H@("`@("`@(&EF('-E
M;&8N;G0H82D@:6X@<V5L9BYG971F:7)S="@G4B<I.@T*("`@("`@("`@("`@
M<F5T=7)N('-E;&8N4BAA*0T*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@
M<V5L9BYG971F:7)S="@G4"<I.@T*("`@("`@("`@("`@<F5T=7)N('-E;&8N
M4"AA*0T*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F;VQL
M;W<H)TDG*3H-"B`@("`@("`@("`@(')E='5R;B!A#0H@("`@("`@(&5L<V4Z
M#0H@("`@("`@("`@("!E>&ET<&=M*"D-"@T*("`@(&1E9B!0*'-E;&8L(&$I
M.@T*("`@("`@("!I9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9FER<W0H)U`G
M*3H-"B`@("`@("`@("`@(&(@/2!S96QF+E$H82D-"B`@("`@("`@("`@(&,@
M/2!S96QF+DXH8BD-"B`@("`@("`@("`@(&0@/2!S96QF+DTH8RD-"B`@("`@
M("`@("`@(')E='5R;B!S96QF+DLH9"D-"B`@("`@("`@96QS93H-"B`@("`@
M("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F(%$H<V5L9BP@82DZ#0H@("`@
M("`@(&EF('-E;&8N;G0H82D@/3T@)R@G.@T*("`@("`@("`@("`@8B`]('-E
M;&8N86-C97!T*"<H)RP@82D-"B`@("`@("`@("`@(&,@/2!S96QF+F%R9W,H
M8BD-"B`@("`@("`@("`@(')E='5R;B!S96QF+F%C8V5P="@G*2<L(&,I#0H@
M("`@("`@(&5L:68@<V5L9BYN="AA*2`]/2`G6R<Z#0H@("`@("`@("`@("!B
M(#T@<V5L9BYA8V-E<'0H)ULG+"!A*0T*("`@("`@("`@("`@8R`]('-E;&8N
M97AP<G-N*&(I#0H@("`@("`@("`@("!R971U<FX@<V5L9BYA8V-E<'0H)UTG
M+"!C*0T*("`@("`@("!E;&EF('-E;&8N;G0H82D@/3T@)VYU;2<Z#0H@("`@
M("`@("`@("!R971U<FX@<V5L9BYA8V-E<'0H)VYU;2<L(&$I#0H@("`@("`@
M(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9O;&QO=R@G42<I.@T*("`@
M("`@("`@("`@<F5T=7)N(&$-"B`@("`@("`@96QS93H-"B`@("`@("`@("`@
M(&5X:71P9VTH*0T*#0H@("`@9&5F(%(H<V5L9BP@82DZ#0H@("`@("`@(&EF
M('-E;&8N;G0H82D@:6X@<V5L9BYG971F:7)S="@G4B<I.@T*("`@("`@("`@
M("`@8B`]('-E;&8N2BAA*0T*("`@("`@("`@("`@8R`]('-E;&8N<F5L;W`H
M8BD-"B`@("`@("`@("`@(')E='5R;B!S96QF+F%D9%]E>'!R<VXH8RD-"B`@
M("`@("`@96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F
M('9A<BAS96QF+"!A*3H-"B`@("`@("`@:68@<V5L9BYN="AA*2`]/2`G:60G
M.@T*("`@("`@("`@("`@8B`]('-E;&8N86-C97!T*"=I9"<L(&$I#0H@("`@
M("`@("`@("!R971U<FX@<V5L9BY**&(I#0H@("`@("`@(&5L<V4Z#0H@("`@
M("`@("`@("!E>&ET<&=M*"D-"@T*("`@(&1E9B!**'-E;&8L(&$I.@T*("`@
M("`@("!I9B!S96QF+FYT*&$I(#T]("=;)SH-"B`@("`@("`@("`@(&(@/2!S
M96QF+F%C8V5P="@G6R<L(&$I#0H@("`@("`@("`@("!C(#T@<V5L9BYE>'!R
M<VXH8BD-"B`@("`@("`@("`@(')E='5R;B!S96QF+F%C8V5P="@G72<L(&,I
M#0H@("`@("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9O;&QO=R@G
M2B<I.@T*("`@("`@("`@("`@<F5T=7)N(&$-"B`@("`@("`@96QS93H-"B`@
M("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F('-I;7!L95]E>'!R<VXH
M<V5L9BP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F
M:7)S="@G<VEM<&QE+65X<')S;B<I.@T*("`@("`@("`@("`@8B`]('-E;&8N
M861D7V5X<')S;BAA*0T*("`@("`@("`@("`@<F5T=7)N('-E;&8N2RAB*0T*
M("`@("`@("!E;'-E.@T*("`@("`@("`@("`@97AI='!G;2@I#0H-"B`@("!D
M968@2RAS96QF+"!A*3H-"B`@("`@("`@:68@<V5L9BYN="AA*2!I;B!S96QF
M+F=E=&9I<G-T*"=R96QO<"<I.@T*("`@("`@("`@("`@8B`]('-E;&8N<F5L
M;W`H82D-"B`@("`@("`@("`@(')E='5R;B!S96QF+F%D9%]E>'!R<VXH8BD-
M"B`@("`@("`@96QI9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9F]L;&]W*"=+
M)RDZ#0H@("`@("`@("`@("!R971U<FX@80T*("`@("`@("!E;'-E.@T*("`@
M("`@("`@("`@97AI='!G;2@I#0H-"B`@("!D968@<F5L;W`H<V5L9BP@82DZ
M#0H@("`@("`@(&EF('-E;&8N;G0H82D@/3T@)SPG.@T*("`@("`@("`@("`@
M8B`]('-E;&8N86-C97!T*"<\)RP@82D-"B`@("`@("`@("`@(')E='5R;B!S
M96QF+DPH8BD-"B`@("`@("`@96QI9B!S96QF+FYT*&$I(#T]("<^)SH-"B`@
M("`@("`@("`@(&,@/2!S96QF+F%C8V5P="@G/B<L(&$I#0H@("`@("`@("`@
M("!R971U<FX@<V5L9BY,*&,I#0H@("`@("`@(&5L:68@<V5L9BYN="AA*2`]
M/2`G/2<Z#0H@("`@("`@("`@("!D(#T@<V5L9BYA8V-E<'0H)STG+"!A*0T*
M("`@("`@("`@("`@<F5T=7)N('-E;&8N86-C97!T*"<])RP@9"D-"B`@("`@
M("`@96QI9B!S96QF+FYT*&$I(#T]("<A)SH-"B`@("`@("`@("`@(&4@/2!S
M96QF+F%C8V5P="@G(2<L(&$I#0H@("`@("`@("`@("!R971U<FX@<V5L9BYA
M8V-E<'0H)STG+"!E*0T*("`@("`@("!E;'-E.@T*("`@("`@("`@("`@97AI
M='!G;2@I#0H-"B`@("!D968@3"AS96QF+"!A*3H-"B`@("`@("`@:68@<V5L
M9BYN="AA*2`]/2`G/2<Z#0H@("`@("`@("`@("!R971U<FX@<V5L9BYA8V-E
M<'0H)STG+"!A*0T*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG
M971F;VQL;W<H)TPG*3H-"B`@("`@("`@("`@(')E='5R;B!A#0H@("`@("`@
M(&5L<V4Z#0H@("`@("`@("`@("!E>&ET<&=M*"D-"@T*("`@(&1E9B!A9&1?
M97AP<G-N*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(&EN('-E
M;&8N9V5T9FER<W0H)W1E<FTG*3H-"B`@("`@("`@("`@(&(@/2!S96QF+G1E
M<FTH82D-"B`@("`@("`@("`@(')E='5R;B!S96QF+DTH8BD-"B`@("`@("`@
M96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F($TH<V5L
M9BP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F:7)S
M="@G861D;W`G*3H-"B`@("`@("`@("`@(&(@/2!S96QF+F%D9&]P*&$I#0H@
M("`@("`@("`@("!C(#T@<V5L9BYT97)M*&(I#0H@("`@("`@("`@("!R971U
M<FX@<V5L9BY-*&,I#0H@("`@("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF
M+F=E=&9O;&QO=R@G32<I.@T*("`@("`@("`@("`@<F5T=7)N(&$-"B`@("`@
M("`@96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F(&%D
M9&]P*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(#T]("<K)SH-
M"B`@("`@("`@("`@(')E='5R;B!S96QF+F%C8V5P="@G*R<L(&$I#0H@("`@
M("`@(&5L:68@<V5L9BYN="AA*2`]/2`G+2<Z#0H@("`@("`@("`@("!R971U
M<FX@<V5L9BYA8V-E<'0H)RTG+"!A*0T*("`@("`@("!E;'-E.@T*("`@("`@
M("`@("`@97AI='!G;2@I#0H-"B`@("!D968@=&5R;2AS96QF+"!A*3H-"B`@
M("`@("`@:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=F86-T;W(G
M*3H-"B`@("`@("`@("`@(&(@/2!S96QF+F9A8W1O<BAA*0T*("`@("`@("`@
M("`@<F5T=7)N('-E;&8N3BAB*0T*("`@("`@("!E;'-E.@T*("`@("`@("`@
M("`@97AI='!G;2@I#0H-"B`@("!D968@3BAS96QF+"!A*3H-"B`@("`@("`@
M:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=M=6QO<"<I.@T*("`@
M("`@("`@("`@8B`]('-E;&8N;75L;W`H82D-"B`@("`@("`@("`@(&,@/2!S
M96QF+F9A8W1O<BAB*0T*("`@("`@("`@("`@<F5T=7)N('-E;&8N3BAC*0T*
M("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F;VQL;W<H)TXG
M*3H-"B`@("`@("`@("`@(')E='5R;B!A#0H@("`@("`@(&5L<V4Z#0H@("`@
M("`@("`@("!E>&ET<&=M*"D-"@T*("`@(&1E9B!M=6QO<"AS96QF+"!A*3H-
M"B`@("`@("`@:68@<V5L9BYN="AA*2!I;B!;)RHG73H-"B`@("`@("`@("`@
M(')E='5R;B!S96QF+F%C8V5P="@G*B<L(&$I#0H@("`@("`@(&EF('-E;&8N
M;G0H82D@:6X@6R<O)UTZ#0H@("`@("`@("`@("!R971U<FX@<V5L9BYA8V-E
M<'0H)R\G+"!A*0T*("`@("`@("!E;'-E.@T*("`@("`@("`@("`@97AI='!G
M;2@I#0H-"B`@("!D968@9F%C=&]R*'-E;&8L(&$I.@T*("`@("`@("!I9B!S
M96QF+FYT*&$I(&EN(%LG*"==.@T*("`@("`@("`@("`@8B`]('-E;&8N86-C
M97!T*"<H)RP@82D-"B`@("`@("`@("`@(&,@/2!S96QF+F5X<')S;BAB*0T*
M("`@("`@("`@("`@<F5T=7)N('-E;&8N86-C97!T*"<I)RP@8RD-"B`@("`@
M("`@96QI9B!S96QF+FYT*&$I(&EN(%LG:60G73H-"B`@("`@("`@("`@(&0@
M/2!S96QF+F%C8V5P="@G:60G+"!A*0T*("`@("`@("`@("`@<F5T=7)N('-E
M;&8N=F%R8V%L;"AD*0T*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@6R=N
M=6TG73H-"B`@("`@("`@("`@(')E='5R;B!S96QF+F%C8V5P="@G;G5M)RP@
M82D-"B`@("`@("`@96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@
M("`@9&5F('9A<F-A;&PH<V5L9BP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H
M82D@:6X@<V5L9BYG971F:7)S="@G2B<I.@T*("`@("`@("`@("`@<F5T=7)N
M('-E;&8N2BAA*0T*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG
M971F:7)S="@G8V%L;"<I.@T*("`@("`@("`@("`@<F5T=7)N('-E;&8N8V%L
M;"AA*0T*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F;VQL
M;W<H)W9A<F-A;&PG*3H-"B`@("`@("`@("`@(')E='5R;B!A#0H@("`@("`@
M(&5L<V4Z#0H@("`@("`@("`@("!E>&ET<&=M*"D-"@T*("`@(&1E9B!C86QL
M*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T
M9FER<W0H)V-A;&PG*3H-"B`@("`@("`@("`@(&(@/2!S96QF+F%C8V5P="@G
M*"<L(&$I#0H@("`@("`@("`@("!C(#T@<V5L9BYA<F=S*&(I#0H@("`@("`@
M("`@("!R971U<FX@<V5L9BYA8V-E<'0H)RDG+"!C*0T*("`@("`@("!E;'-E
M.@T*("`@("`@("`@("`@97AI='!G;2@I#0H-"B`@("!D968@87)G<RAS96QF
M+"!A*3H-"B`@("`@("`@:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T
M*"=A<F<M;&ES="<I.@T*("`@("`@("`@("`@<F5T=7)N('-E;&8N87)G7VQI
M<W0H82D-"B`@("`@("`@96QI9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9F]L
M;&]W*"=A<F<M;&ES="<I.@T*("`@("`@("`@("`@<F5T=7)N(&$-"B`@("`@
M("`@96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F(&%R
M9U]L:7-T*'-E;&8L(&$I.@T*("`@("`@("!I9B!S96QF+FYT*&$I(&EN('-E
M;&8N9V5T9FER<W0H)V%R9RUL:7-T)RDZ#0H@("`@("`@("`@("!B(#T@<V5L
M9BYE>'!R<VXH82D-"B`@("`@("`@("`@(')E='5R;B!S96QF+D\H8BD-"B`@
M("`@("`@96QS93H-"B`@("`@("`@("`@(&5X:71P9VTH*0T*#0H@("`@9&5F
M($\H<V5L9BP@82DZ#0H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@6R<L)UTZ
M#0H@("`@("`@("`@("!B(#T@<V5L9BYA8V-E<'0H)RPG+"!A*0T*("`@("`@
M("`@("`@8R`]('-E;&8N97AP<G-N*&(I#0H@("`@("`@("`@("!D(#T@<V5L
M9BY/*&,I#0H@("`@("`@("`@("!R971U<FX@9`T*("`@("`@("!E;&EF('-E
M;&8N;G0H82D@:6X@<V5L9BYG971F;VQL;W<H)T\G*3H-"B`@("`@("`@("`@
M(')E='5R;B!A#0H@("`@("`@(&5L<V4Z#0H@("`@("`@("`@("!E>&ET<&=M
$*"D-"G5R
`
end
SHAR_EOF
  (set 20 16 10 23 00 16 10 'parse.py'; eval "$shar_touch") &&
  chmod 0644 'parse.py'
if test $? -ne 0
then ${echo} 'restore of parse.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'parse.py: MD5 check failed'
       ) << \SHAR_EOF
65f6c98ea0fba35f84a52c40d4eddcb5  parse.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'parse.py'` -ne 19759 && \
  ${echo} 'restoration warning:  size of parse.py is not 19759'
  fi
fi
# ============= queue.py ==============
if test -f 'queue.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING queue.py (file already exists)'
else
${echo} 'x - extracting queue.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 queue.py
M8VQA<W,@475E=64H;V)J96-T*3H-"@T*("`@(&1E9B!?7VEN:71?7RAS96QF
M*3H-"B`@("`@("`@<V5L9BYI=&5M<R`](%M=#0H@("`@("`@('-E;&8N:2`]
M(&QE;BAS96QF+FET96US*0T*#0H@("`@9&5F(&ES16UP='DH<V5L9BDZ#0H@
M("`@("`@(')E='5R;B!S96QF+FET96US(#T](%M=#0H-"B`@("!D968@96YQ
M=65U92AS96QF+"!I=&5M*3H-"B`@("`@("`@<V5L9BYI=&5M<RYI;G-E<G0H
M,"P@:71E;2D-"B`@("`@("`@<V5L9BYI("L](#$-"@T*("`@(&1E9B!D97%U
M975E*'-E;&8I.@T*("`@("`@("!S96QF+FD@+3T@,0T*("`@("`@("!R971U
M<FX@<V5L9BYI=&5M<RYP;W`H*0T*#0H@("`@9&5F('-I>F4H<V5L9BDZ#0H@
M("`@("`@(')E='5R;B!L96XH<V5L9BYI=&5M<RD-"@T*("`@(&1E9B!P<FEN
M='$H<V5L9BDZ#0H@("`@("`@('!R:6YT('-E;&8N:71E;7,-"@T*("`@(&1E
M9B!Q9G)O;G0H<V5L9BDZ#0H@("`@("`@(')E='5R;B!S96QF+FET96US6VQE
M;BAS96QF+FET96US*2TQ70T*#0H@("`@9&5F(&YE>'1T;VME;BAS96QF*3H-
M"B`@("`@("`@:68@,"`\('-E;&8N:2`\/2!L96XH<V5L9BYI=&5M<RDZ#0H@
M("`@("`@("`@("!R971U<FX@<V5L9BYI=&5M<UMS96QF+FDM,5T-"@T*("`@
M(&1E9B!A8V-E<'0H<V5L9BDZ#0H@("`@("`@('-E;&8N:2`M/2`Q#0H-"B`@
M("!D968@:6YD97AE9"AS96QF+"!N*3H-"B`@("`@("`@:68@,"`\(&X@/#T@
M;&5N*'-E;&8N:71E;7,I.@T*("`@("`@("`@("`@<F5T=7)N('-E;&8N:71E
);7-;;BTQ70T*
`
end
SHAR_EOF
  (set 20 16 10 21 21 03 23 'queue.py'; eval "$shar_touch") &&
  chmod 0644 'queue.py'
if test $? -ne 0
then ${echo} 'restore of queue.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'queue.py: MD5 check failed'
       ) << \SHAR_EOF
f32e6cc2a545b538eb1a43317cf2729a  queue.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'queue.py'` -ne 774 && \
  ${echo} 'restoration warning:  size of queue.py is not 774'
  fi
fi
if rm -fr ${lock_dir}
then ${echo} 'x - removed lock directory `'${lock_dir}\''.'
else ${echo} 'x - failed to remove lock directory `'${lock_dir}\''.'
  exit 1
fi
exit 0
