#!/bin/sh
# This is a shell archive (produced by GNU sharutils 4.7).
# To extract the files from this archive, save it to some FILE, remove
# everything before the `#!/bin/sh' line above, then type `sh FILE'.
#
lock_dir=_sh20090
# Made on 2016-11-11 22:37 EST by <n00886248@osprey.unfcsd.unf.edu>.
# Source directory was `/home/48/n00886248/Compilers/proj3'.
#
# Existing files will *not* be overwritten, unless `-c' is specified.
#
# This shar contains:
# length mode       name
# ------ ---------- ------------------------------------------
#   2951 -rw-r--r-- doc.txt
#   1401 -rwxr-xr-x f3.py
#   2158 -rw-r--r-- findcmnts.py
#   3325 -rw-r--r-- lexical.py
#     55 -rw-r--r-- makefile
#     28 -rwxr-xr-x p3
#  17250 -rw-r--r-- parse.py
#   1219 -rw-r--r-- Proj3.py
#    740 -rw-r--r-- queue.py
#      7 -rw-r--r-- sample.txt
#   5605 -rw-r--r-- Semantics.py
#    130 -rw-r--r-- test1.txt
#    131 -rw-r--r-- test.txt
#
MD5SUM=${MD5SUM-md5sum}
f=`${MD5SUM} --version | egrep '^md5sum .*(core|text)utils'`
test -n "${f}" && md5check=true || md5check=false
${md5check} || \
  echo 'Note: not verifying md5sums.  Consider installing GNU coreutils.'
save_IFS="${IFS}"
IFS="${IFS}:"
gettext_dir=FAILED
locale_dir=FAILED
first_param="$1"
for dir in $PATH
do
  if test "$gettext_dir" = FAILED && test -f $dir/gettext \
     && ($dir/gettext --version >/dev/null 2>&1)
  then
    case `$dir/gettext --version 2>&1 | sed 1q` in
      *GNU*) gettext_dir=$dir ;;
    esac
  fi
  if test "$locale_dir" = FAILED && test -f $dir/shar \
     && ($dir/shar --print-text-domain-dir >/dev/null 2>&1)
  then
    locale_dir=`$dir/shar --print-text-domain-dir`
  fi
done
IFS="$save_IFS"
if test "$locale_dir" = FAILED || test "$gettext_dir" = FAILED
then
  echo=echo
else
  TEXTDOMAINDIR=$locale_dir
  export TEXTDOMAINDIR
  TEXTDOMAIN=sharutils
  export TEXTDOMAIN
  echo="$gettext_dir/gettext -s"
fi
if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null
then if (echo -n test; echo 1,2,3) | grep n >/dev/null
     then shar_n= shar_c='
'
     else shar_n=-n shar_c= ; fi
else shar_n= shar_c='\c' ; fi
f=shar-touch.$$
st1=200112312359.59
st2=123123592001.59
st2tr=123123592001.5 # old SysV 14-char limit
st3=1231235901

if touch -am -t ${st1} ${f} >/dev/null 2>&1 && \
   test ! -f ${st1} && test -f ${f}; then
  shar_touch='touch -am -t $1$2$3$4$5$6.$7 "$8"'

elif touch -am ${st2} ${f} >/dev/null 2>&1 && \
   test ! -f ${st2} && test ! -f ${st2tr} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$1$2.$7 "$8"'

elif touch -am ${st3} ${f} >/dev/null 2>&1 && \
   test ! -f ${st3} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$2 "$8"'

else
  shar_touch=:
  echo
  ${echo} 'WARNING: not restoring timestamps.  Consider getting and'
  ${echo} 'installing GNU `touch'\'', distributed in GNU coreutils...'
  echo
fi
rm -f ${st1} ${st2} ${st2tr} ${st3} ${f}
#
if test ! -d ${lock_dir}
then : ; else ${echo} 'lock directory '${lock_dir}' exists'
  exit 1
fi
if mkdir ${lock_dir}
then ${echo} 'x - created lock directory `'${lock_dir}\''.'
else ${echo} 'x - failed to create lock directory `'${lock_dir}\''.'
  exit 1
fi
# ============= doc.txt ==============
if test -f 'doc.txt' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING doc.txt (file already exists)'
else
${echo} 'x - extracting doc.txt (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 doc.txt
M*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ
M*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*@T*#0I.86UE.B!2
M86IA;B!086YD>6$@;C`P.#@V,C0X#0H-"@T*0VQA<W,Z($-/4#0V,C`@0T].
M4U1254-424].($]&($Q!3D=504=%(%1204Y33$%43U)3#0H-"E!R;VIE8W0@
M,R!396UA;G1I8W,@06YA;'EZ97(-"@T*1FEL97,@26YC;'5D960Z#0H-"C$N
M(&8S+G!Y("AS;W5R8V4@9FEL92D-"C(N(&QE>&EC86PN<'D@*'-O=7)C92!F
M:6QE*0T*,RX@9FEN9&-M;G1S+G!Y("AS;W5R8V4@9FEL92D-"C0N('%U975E
M+G!Y("AS;W5R8V4@9FEL92D-"C4N('!A<G-E+G!Y("AS;W5R8V4@9FEL92D-
M"C8N(%-E;6%N=&EC<RYP>2`H<V]U<F-E(&9I;&4I#0HW+B!M86ME9FEL92`-
M"C@N('`S("AT;R!R=6X@=&AE('-O=7)C92!F:6QE*0T*.2X@=&5S="YT>'0@
M*'1E<W0@9FEL92D-"C$P+B!D;V,N='AT("A$;V-U;65N=&%T:6]N(&9I;&4I
M(`T*,3$N('-A;7!L92YT>'0@*&]U='!U="!F:6QE(&9O<B!T:&4@9VEV96X@
M=&5S="!F:6QE*2`-"@T*2&]W('1O(')U;B!T:&4@4')O9W)A;3H-"@T*5&AI
M<R!P<F]G<F%M+"!S:6YC92!P>71H;VX@;&%N9W5A9V4@:7,@=7-E9"P@9&]E
M<R!N;W0@;F5E9"!T;R!E>&5C=71E(&UA:V4@8V]M;6%N9"X-"E1H:7,@<')O
M9W)A;2!C86X@8F4@97AE8W5T960@8GD@='EP:6YG("<N+W`S('1E<W0N='AT
M)RX@#0I);G-T96%D(&]F(&UY('1E<W0@9FEL92P@=7-E<G,@8V%N('5S92!T
M:&5I<B!O=VX@=&5X="!O<B!L:6YU>"!F:6QE(&%S(&%N(&-O;6UA;F0@;&EN
M92!A<F=U;65N="X-"@T*#0I'96YE<F%L($1I<V-R:7!T:6]N.@T*#0I4:&4@
M9C,N<'D@86-C97!T<R!A(&9I;&4@9G)O;2!C;VUM86YD(&QI;F4N(`T*270@
M<F5C;V=N:7IE<R!I9B!T:&4@9FEL92!I<R!N;W0@<')O=FED960@:6X@8V]M
M;6%N9"!L:6YE(&%R9W5M96YT<RP@86YD('!R:6YT<R!A(&UE<W-A9V4N#0I)
M="!S<&QI=',@=&AE(&-O;G1E;G0@9G)O;2!G:79E;B!F:6QE(&EN=&\@;6%N
M>2!S96YT96YC97,@86YD('-T;W)E('1H96T@:6X@86X@87)R87DN(`T*3VYE
M("=F;W(@;&]O<"<@<G5N<R!T:')O=6=H('1H870@87)R87DL(&%N9"!C86QL
M<R!A(&9U;F-T:6]N(&YA;65D("=F:6YD8VUN=',G(&%N9"`G;&5X:6-A;"<@
M=VET:"!P87-S:6YG(&]N92!L:6YE(&%T(&$@=&EM92X@#0I4:&4@)VQE>&EC
M86PG('5S97,@=&AE('-T<FEN9R!T:&%T(&ES(')E='5R;F5D(&)Y("=F:6YD
M8VUN=',G(&9U;F-T:6]N+2!A9G1E<B!R96UO=FEN9R!C;VUM96YT<R!I;F-L
M=61I;F<@;F5S=&5D(&]N97,N#0I);B`G9FEN9&-M;G1S)RP@=&AE<F4@:7,@
M82!G;&]B86P@=F%R:6%B;&4@;F%M960@)V-O=6YT97(G('=H:6-H(&ME97!S
M('1R86-K(&]F('1H92!N=6UB97(@;V8@;75L=&EL:6YE(&-O;6UE;G1S+@T*
M57!O;B!R96-E:79I;F<@<W1R:6YG(&9R;VT@)V9I;F1C;6YT<R<L('1H92`G
M;&5X:6-A;"<@87!P;&EE<R!D:69F97)E;G0@<F5G=6QA<B!E>'!R97-S:6]N
M<R!O;B!T:&4@<W1R:6YG+"!A;F0@#0H)<V5P97)A=&5S('1H96T@:6YT;R!T
M;VME;G,L(&%N9"!P<FEN=',@=&AE;2X-"@EI+F4@:60L(&YU;2P@;W!E<F%T
M;W)S+"!P87)E;G1H97-I<RP@:V5Y=V]R9',L(&5T8RX-"E1H92`G;&5X:6-A
M;"<@=7-E<R!T:&4@9G5N8W1I;VX@)V9I;F1K97ES)R!T;R!S97!E<F%T92!K
M97EW;W)D<R!F<F]M(&ED<RX@#0I)="!C86QL<R`G9FEN9&ME>7,G('=H96YE
M=F5R(&ET(&9I;F1S(&%N(&ED+"!A;F0@)V9I;F1K97ES)R!D971E<FUI;F5S
M(&%N9"!P<FEN=',@:68@:70@:7,@86X@:60@;W(@82!K97EW;W)D+@T*1G5N
M8W1I;VX@)V9I;F1K97ES)R!U<V5S(&$@9VQO8F%L('9A<FEA8FQE("=K97EW
M;W)D<R<@=VAI8V@@:&%S(&%L;"!T:&4@:V5Y=V]R9',@<W1O<F5D(&EN(&%N
M(&%R<F%Y+@T*5&AE("=L97AI8V%L)R!R96-O9VYI>F5S(&%L;"!D:69F97)E
M;G0@=&]K96YS(&%N9"!E<G)O<BP@:68@86YY+"!A;F0@:70@<')I;G1S('1H
M96T@;VYE(&)Y(&]N92!I;B!T:&4@<V%M92!O<F1E<B!T:&5Y(&-A;64N#0I5
M<&]N(')E8V5I=FEN9R!T;VME;G,@9G)O;2!P<F]J96-T(#$L('!A<G-E+G!Y
M(&9I;&4@9V]E<R!T:')O=6=H(&=R86UM87(@<G5L97,@;V8@0RT@;&%N9W5A
M9V4@=FEA(&UE=&AO9',@:6X@8VQA<W,@4&%R<VEN9RX@#0I)="!H87,@9&EC
M=&EO;F%R:65S('1O(&AO;&0@;VX@=&\@=&AE(&9I<G-T<R!A;F0@9F]L;&]W
M<R!O9B!T:&4@9W)A;6UA<B!R=6QE(&YO;BUT97)M:6YA;',N(`T*5&AE('!R
M;V=R86T@=7-E<R!T:&4@8W5R<F5N="!T;VME;BP@9FER<W1S+"!A;F0@9F]L
M;&]W<R!A<R!A('!A=&@@=&\@=')A=F5R<V4@=&AR;W5G:"!M971H;V1S(&EN
M('1H92!C;&%S<RX@270@:&%S(&%N(&]B:F5C="!Q=65U92!O9B!C;&%S<R!1
M=65U92!T;R!S=&]R92!A;&P@=&AE('1O:V5N<R!F<F]M('!R;VIE8W0@,2X@
M#0I/;F-E('1H92!C=7)R96YT('1O:V5N(&ES(&]N(&9I<G-T(&EN9&5X(&]F
M('1H92!Q=65U92P@86YD(&ET(&ES("0L(&ET('-T87)T<R!E>&5C=71I;F<@
M=&AE(&-O9&4@;V8@8VQA<W,@4V5M86YT:6-S(&9O<B!P<F]J96-T(#,N#0I4
M:&4@<V5M86YT:6-S(&-L87-S(&AA<R!S979E<F%L(&-H96-K<RX@268@86YY
M(&]N92!O9B!T:&5M(&ES(&9A:6QE9"P@:70@<F5T=7)N<R!&86QS92!A="!T
M:&4@96YD('1O('1H92!M86EN('!R;V=R86TN#0I4:&4@;6%I;B!P<F]G<F%M
M('1H96X@<')I;G0@04-#15!4(&]R(%)%2D5#5"!B87-E9"!O;B!T:&4@<F5T
M=7)N('9A;'5E(&9R;VT@<V5M86YT:6-S(&9U;F-T:6]N(&-H96-K<R!I<R!4
M<G5E(&]R($9A;'-E(')E<W!E8W1I=F5L>2X-"@T*#0H-"BHJ*BHJ*BHJ*BHJ
M*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ
:*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ*BHJ#0HJ
`
end
SHAR_EOF
  (set 20 16 11 11 22 36 57 'doc.txt'; eval "$shar_touch") &&
  chmod 0644 'doc.txt'
if test $? -ne 0
then ${echo} 'restore of doc.txt failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'doc.txt: MD5 check failed'
       ) << \SHAR_EOF
f63399800d8068f5b97c0274d5f84572  doc.txt
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'doc.txt'` -ne 2951 && \
  ${echo} 'restoration warning:  size of doc.txt is not 2951'
  fi
fi
# ============= f3.py ==============
if test -f 'f3.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING f3.py (file already exists)'
else
${echo} 'x - extracting f3.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 f3.py
M:6UP;W)T('-Y<PII;7!O<G0@4V5M86YT:6-S"FEM<&]R="!L97AI8V%L"FEM
M<&]R="!Q=65U90II;7!O<G0@9FEN9&-M;G1S"FEM<&]R="!P87)S90H*"FEF
M(%]?;F%M95]?(#T]("=?7VUA:6Y?7R<Z"B`@("!L:6YE<R`](%M="B`@("!N
M97=L:6YE<R`](%M="B`@("!T;VME;G,@/2`P"B`@("!D(#T@>WT*("`@('-Y
M;2`]>WT*("`@('$@/2!Q=65U92Y1=65U92@I"B`@("!T<GDZ"B`@("`@("`@
M=VET:"!O<&5N*'-Y<RYA<F=V6S%=+"`G<B<I(&%S(&9I;&4Z"B`@("`@("`@
M("`@('!A<W,*("`@("`@("`@("`@9F]R(&4@:6X@9FEL93H*("`@("`@("`@
M("`@("`@(&QI;F5S+F%P<&5N9"AE+G)S=')I<"@G7&XG*2D*("`@("`@("`@
M("`@9FEL92YC;&]S92@I"B`@("!E>&-E<'0Z"B`@("`@("`@<')I;G0@)U1H
M:7,@<')O9W)A;2!N965D<R!A(&9I;&4@87)G=6UE;G0N)PH@("`@:68@;&EN
M97,Z"B`@("`@("`@9F]R(&QI;F4@:6X@;&EN97,Z"B`@("`@("`@("`@(&EF
M(&QE;BAL:6YE*2`^(#`Z"B`@("`@("`@("`@("`@("!L:6YE(#T@9FEN9&-M
M;G1S+F9I;F1C;6YT<RAL:6YE*0H@("`@("`@("`@("`@("`@<2P@92P@<WEM
M+"!T<G5D(#T@;&5X:6-A;"YL97AI8V%L*&QI;F4L('$L(&0I"B`@("`@("`@
M("`@("`@("!D+G5P9&%T92AE*0H@("`@("`@("`@("`@("`@;B`]('$N<VEZ
M92@I("T@=&]K96YS"B`@("`@("`@("`@("`@("!I9B!E.@H@("`@("`@("`@
M("`@("`@("`@(&YQ(#T@6UT*("`@("`@("`@("`@("`@("`@("!W:&EL92!N
M(#X],3H*("`@("`@("`@("`@("`@("`@("`@("`@;G$N87!P96YD*'$N:6YD
M97AE9"AN*2D*("`@("`@("`@("`@("`@("`@("`@("`@;BT],0H@("`@("`@
M("`@("`@("`@("`@(&EF(&YQ.@H@("`@("`@("`@("`@("`@("`@("`@("!N
M97=L:6YE<RYA<'!E;F0H)R`G+FIO:6XH;G$I*0H@("`@("`@("`@("`@("`@
M("`@('1O:V5N<R`K/2!L96XH;G$I"B`@("`@("`@(R!F;W(@;&EN92!I;B!N
M97=L:6YE<SH*("`@("`@("`C("`@("!P<FEN="!L:6YE"B`@("`@("`@:68@
M;F]T('$N:7-%;7!T>2@I(&%N9"!D.@H@("`@("`@("`@("!Q+F5N<75E=64H
M)R0G*0H@("`@("`@("`@("!D+G5P9&%T92A[)R0G.B`G)"=]*0H@("`@("`@
M("`@("!P(#T@<&%R<V4N4&%R<VEN9RAQ+&0I"B`@("`@("`@("`@(',@/2!3
M96UA;G1I8W,N<V5M86YT:6-S*'$L9"QS>6TL;F5W;&EN97,I"B`@("`@("`@
M("`@(&EF('`N<W1A<G0H*3H*("`@("`@("`@("`@("`@(&EF(',N<W1A<G0H
M*3H*("`@("`@("`@("`@("`@("`@("!P<FEN="=!0T-%4%0G"B`@("`@("`@
M("`@("`@("!E;'-E.@H@("`@("`@("`@("`@("`@("`@('!R:6YT)U)%2D5#
M5"<*("`@("`@("`@("`@96QS93H*("`@("`@("`@("`@("`@('!R:6YT("=2
&14I%0U0G
`
end
SHAR_EOF
  (set 20 16 11 11 22 15 26 'f3.py'; eval "$shar_touch") &&
  chmod 0755 'f3.py'
if test $? -ne 0
then ${echo} 'restore of f3.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'f3.py: MD5 check failed'
       ) << \SHAR_EOF
a6592731cbbb4b68d39ae06a5a55346f  f3.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'f3.py'` -ne 1401 && \
  ${echo} 'restoration warning:  size of f3.py is not 1401'
  fi
fi
# ============= findcmnts.py ==============
if test -f 'findcmnts.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING findcmnts.py (file already exists)'
else
${echo} 'x - extracting findcmnts.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 findcmnts.py
M[[N_:6UP;W)T(')E"@IC;W5N=&5R(#T@,`H*"F1E9B!F:6YD8VUN=',H;&QI
M;F4I.@H@("`@(B(B"B`@("!)="!F:6YD<R!A;F0@<F5M;W9E<R!D:69F97)E
M;G0@='EP97,@;V8@8V]M;65N=',@9G)O;2!T:&4@9VEV96X@<W1R:6YG+@H@
M("`@.G!A<F%M(&QL:6YE.B!)="!I<R!A(&=I=F5N('-T<FEN9RX*("`@(#IR
M971U<FXZ($ET(')E='5R;G,@=&AE('-T<FEN9R!A9G1E<B!S=')I<&EN9R!O
M9F8@8V]M;65N=',N"B`@("`B(B(*("`@(&=L;V)A;"!C;W5N=&5R"B`@("!C
M;W5N=&5R,B`](&-O=6YT97(*("`@('!A=#,@/2!R92YC;VUP:6QE*"<H/SHH
M6UPO75M<*ETI?"A;7"I=6UPO72E\*%M<+UU;7"]=*2DG*0H@("`@;6QC<R`]
M(%M="B`@("!S;&,@/2!;70H@("`@;6QC92`](%M="B`@("!I;F1X<R`](%M=
M"B`@("!B;"`]($9A;'-E"B`@("!I="`](')E+F9I;F1I=&5R*'!A=#,L(&QL
M:6YE*0H@("`@8VAA;F=E(#T@1F%L<V4*("`@(&9O<B!M871C:"!I;B!I=#H*
M("`@("`@("!I9B!M871C:"YG<F]U<"@I.@H@("`@("`@("`@("!I;F1X<RYA
M<'!E;F0H;6%T8V@N<W1A<G0H*2D*("`@("`@("`@("`@:68@;6%T8V@N9W)O
M=7`H*2`]/2`G+RHG.@H@("`@("`@("`@("`@("`@;6QC<RYA<'!E;F0H;6%T
M8V@N9W)O=7`H*2D*("`@("`@("`@("`@("`@(&UL8V4N87!P96YD*"<G*0H@
M("`@("`@("`@("`@("`@<VQC+F%P<&5N9"@G)RD*("`@("`@("`@("`@("`@
M(&-O=6YT97(@*ST@,0H@("`@("`@("`@("!E;&EF(&UA=&-H+F=R;W5P*"D@
M/3T@)RHO)SH*("`@("`@("`@("`@("`@(&UL8W,N87!P96YD*"<G*0H@("`@
M("`@("`@("`@("`@;6QC92YA<'!E;F0H;6%T8V@N9W)O=7`H*2D*("`@("`@
M("`@("`@("`@('-L8RYA<'!E;F0H)R<I"B`@("`@("`@("`@("`@("!I9B!C
M;W5N=&5R(#X@,#H*("`@("`@("`@("`@("`@("`@("!C;W5N=&5R("T](#$*
M("`@("`@("`@("`@("`@("`@("!C:&%N9V4@/2!4<G5E"B`@("`@("`@("`@
M(&5L<V4Z"B`@("`@("`@("`@("`@("!M;&-S+F%P<&5N9"@G)RD*("`@("`@
M("`@("`@("`@(&UL8V4N87!P96YD*"<G*0H@("`@("`@("`@("`@("`@<VQC
M+F%P<&5N9"AM871C:"YG<F]U<"@I*0H@("`@("`@("`@("!B;"`](%1R=64*
M("`@(&YW;&EN92`]("<G"B`@("!O;F-E(#T@5')U90H@("`@:68@;F]T(&)L
M.@H@("`@("`@(&EF(&-O=6YT97(@/B`P.@H@("`@("`@("`@("!R971U<FX@
M)R<*("`@("`@("!R971U<FX@;&QI;F4*("`@(&5L:68@;&5N*&EN9'AS*2`]
M/2`Q(&%N9"!M;&-E6S!=(&%N9"!C;W5N=&5R(#T](#`@86YD(&YO="!C:&%N
M9V4Z"B`@("`@("`@<F5T=7)N(&QL:6YE"B`@("!E;'-E.@H@("`@("`@(&D@
M/2`P"B`@("`@("`@9F]R(&EN9&5X(&EN(&EN9'AS.@H@("`@("`@("`@("!I
M9B!M;&-S6VE=(&]R('-L8UMI73H*("`@("`@("`@("`@("`@(&EF(&]N8V4Z
M"B`@("`@("`@("`@("`@("`@("`@;G=L:6YE("L](&QL:6YE6SII;F1E>%T*
M("`@("`@("`@("`@("`@("`@("!O;F-E(#T@1F%L<V4*("`@("`@("`@("`@
M("`@(&EF(&UL8W,Z"B`@("`@("`@("`@("`@("`@("`@8V]U;G1E<C(@*ST@
M,0H@("`@("`@("`@("!E;&EF(&UL8V5;:5TZ"B`@("`@("`@("`@("`@("!I
M9B!C;W5N=&5R,B`]/2`P.@H@("`@("`@("`@("`@("`@("`@(&EF(&D@*R`Q
M(#T](&QE;BAI;F1X<RDZ"B`@("`@("`@("`@("`@("`@("`@("`@(&YW;&EN
M92`K/2!L;&EN95MI;F1E>#I="B`@("`@("`@("`@("`@("`@("`@96QS93H*
M("`@("`@("`@("`@("`@("`@("`@("`@;G=L:6YE("L](&QL:6YE6VEN9&5X
M.FEN9'AS6VD@*R`Q75T*("`@("`@("`@("`@("`@(&EF(&-O=6YT97(R(#X@
M,#H*("`@("`@("`@("`@("`@("`@("!C;W5N=&5R,B`M/2`Q"B`@("`@("`@
M("`@("`@("`@("`@:68@8V]U;G1E<C(@/3T@,#H*("`@("`@("`@("`@("`@
M("`@("`@("`@:68@:2`K(#$@/3T@;&5N*&EN9'AS*3H*("`@("`@("`@("`@
M("`@("`@("`@("`@("`@(&YW;&EN92`K/2!L;&EN95MI;F1E>"`K(#(Z70H@
M("`@("`@("`@("`@("`@("`@("`@("!E;'-E.@H@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@;G=L:6YE("L](&QL:6YE6VEN9&5X("L@,CII;F1X<UMI
K("L@,5U="B`@("`@("`@("`@(&D@*ST@,0H@("`@<F5T=7)N(&YW;&EN95MI
`
end
SHAR_EOF
  (set 20 16 11 11 20 04 20 'findcmnts.py'; eval "$shar_touch") &&
  chmod 0644 'findcmnts.py'
if test $? -ne 0
then ${echo} 'restore of findcmnts.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'findcmnts.py: MD5 check failed'
       ) << \SHAR_EOF
f3c3c62f64aa8818886623c345a2562c  findcmnts.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'findcmnts.py'` -ne 2158 && \
  ${echo} 'restoration warning:  size of findcmnts.py is not 2158'
  fi
fi
# ============= lexical.py ==============
if test -f 'lexical.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING lexical.py (file already exists)'
else
${echo} 'x - extracting lexical.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 lexical.py
M:6UP;W)T(')E"@IK97EW;W)D<R`](%LG96QS92<L("=I9B<L("=W:&EL92<L
M("=R971U<FXG+"`G:6YT)RP@)V9L;V%T)RP@)W9O:60G70IS>6T@/2![?0IT
M<G5E9&5S8R`](%LG97)R;W(Z)RP*("`@("`@("`@("`@)V9L;V%T.B<L("=F
M;&]A=#HG+`H@("`@("`@("`@("`G;G5M.B<L("=N=6TZ)RP*("`@("`@("`@
M("`@)V9L;V%T.B<L("=F;&]A=#HG+`H@("`@("`@("`@("`G;G5M.B<L("=N
M=6TZ)RP*("`@("`@("`@("`@)V5R<F]R)RP@)V5R<F]R.B<L("=O<#HG+"`G
M;W`Z)RP@)V5R<F]R)RP@)R<L("=O<#HG+"`G)UT*"F1E9B!L97AI8V%L*&QL
M:6YE+"!Q+"!D*3H*("`@("(B(DET('-E<&%R871E<R!A;F0@<')I;G1S(&$@
M<W1R:6YG(&EN=&\@:61S+"!K97EW;W)D<RP@;G5M8F5R<RP@86YD(&UA;GD@
M9&EF9F5R96YT('1O:V5N<RX*("`@($%R9W,Z"B`@("`@("`@;&QI;F4Z($ET
M(&ES(&$@:6YP=70@<W1R:6YG+@H@("`@("`@('$Z($ET(&ES(&%N(&]B:F5C
M="!O9B!C;&%S<R!1=65U90H@("`@4F5T=7)N<SH*("`@("`@("!.;W1H:6YG
M"B`@("`B(B(*("`@('1R=60@/2![?0H@("`@:68@;&5N*&QL:6YE*2`^(#`Z
M"B`@("`@("`@9&5S8R`](%LG97)R;W(G+`H@("`@("`@("`@("`@("`@)VYU
M;2<L("=N=6TG+`H@("`@("`@("`@("`@("`@)VYU;2<L("=N=6TG+`H@("`@
M("`@("`@("`@("`@)VYU;2<L("=N=6TG+`H@("`@("`@("`@("`@("`@)VYU
M;2<L("=N=6TG+`H@("`@("`@("`@("`@("`@)V5R<F]R)RP@)V5R<F]R)RP@
M)V]P)RP@)V]P)RP@)V5R<F]R)RP@)R<L("=O<"<L("<G70H@("`@("`@(&D@
M/2`P"B`@("`@("`@<&%T,B`](')E+F-O;7!I;&4H)R<G*#\Z*"@_/#U;02U$
M1BU:82UD9BUZ72E;7D$M6F$M>EPA7#Q</EQ;7%U<>UQ]7"A<*5P]7"M<+5PL
M7#M<*EPO7'-=6UY<<UTJ*7P@(R`Q"B`@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@*"@_/#U;7'-<*UPM7"I<+UP]72E;7&1=*UM<+EU;7&1=*RA;165=
M6UPK7"U<9%U;7&1=*BD_*7P@(R`R("8@,PH@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("@H/SP]6UQS7"M<+5PJ7"]</5TI6UQD72LH6T5E75M<*UPM
M7&1=6UQD72HI/RE\(",@-"`F(#4*("`@("`@("`@("`@("`@("`@("`@("`@
M("`@("`H6UQD72M;7"Y=6UQD72LH6T5E75M<*UPM7&1=6UQD72HI/RE\(",@
M-B`F(#<*("`@("`@("`@("`@("`@("`@("`@("`@("`@("`H6UQD72LH6T5E
M75M<*UPM7&1=6UQD72HI/RE\(",@."`F(#D*("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`H*#\\(5QD*5M<+ET_6UQD72I;165=6RLM73];7&1=*RE\
M(",Q,`H@("`@("`@("`@("`@("`@("`@("`@("`@("`@("@H/SP]7&0I6UXP
M+3E%95PN7'-<.UPL7"E<*%Q=7%M<>UQ]7"I<*UPM7"]=6UY<.UPL7"E<*%Q=
M7%M<>UQ]72HI?"`C,3$*("`@("`@("`@("`@("`@("`@("`@("`@("`@("`H
M6UP\7#Y<*UPM7"I<+UP]72E\(",@,3(*("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`H6UP\7#Y<*UPM7"I<+UP]7"%=6UP]72E\(",Q,PH@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("A;7"%<+ETI?"`C,30*("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`H6UPL7#M=*7P@(R`Q-0H@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("A;7%M<75Q[7'U<*%PI72E\(",@,38*("`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`H6T$M6F$M>ETK*2DG)R<L(')E
M+E@I("`C(#$W"B`@("`@("`@:70@/2!R92YF:6YD86QL*'!A=#(L(&QL:6YE
M*0H@("`@("`@(&9O<B!M871C:"!I;B!I=#H*("`@("`@("`@("`@;B`](#`*
M("`@("`@("`@("`@9F]R(&D@:6X@;6%T8V@Z"B`@("`@("`@("`@("`@("!I
M9B!I.@H@("`@("`@("`@("`@("`@("`@(&EF(&X@/3T@,38Z"B`@("`@("`@
M("`@("`@("`@("`@("`@(&4@/2!F:6YD:V5Y<RAI+"!Q+"!D*0H@("`@("`@
M("`@("`@("`@("`@("`@("!D+G5P9&%T92AE*0H@("`@("`@("`@("`@("`@
M("`@(&5L<V4Z"B`@("`@("`@("`@("`@("`@("`@("`@(&EF(#`@/"!N(#P@
M.3H*("`@("`@("`@("`@("`@("`@("`@("`@("`@('$N96YQ=65U92AI*0H@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@9"YU<&1A=&4H>VDZ(&1E<V-;
M;EU]*0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@=')U9"YU<&1A=&4H
M>VDZ=')U961E<V-;;EU]*0H@("`@("`@("`@("`@("`@("`@("`@("!E;&EF
M(&X@/3T@,3(Z"B`@("`@("`@("`@("`@("`@("`@("`@("`@("!Q+F5N<75E
M=64H:5LP72D*("`@("`@("`@("`@("`@("`@("`@("`@("`@('$N96YQ=65U
M92AI6S%=*0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@9"YU<&1A=&4H
M>VE;,%TZ(&E;,%U]*0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@=')U
M9"YU<&1A=&4H>VE;,%TZ(&E;,%U]*0H@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@9"YU<&1A=&4H>VE;,5TZ(&E;,5U]*0H@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@=')U9"YU<&1A=&4H>VE;,5TZ(&E;,5U]*0H@("`@("`@
M("`@("`@("`@("`@("`@("!E;'-E.@H@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@<2YE;G%U975E*&DI"B`@("`@("`@("`@("`@("`@("`@("`@("`@
M("!D+G5P9&%T92A[:3H@:7TI"B`@("`@("`@("`@("`@("`@("`@("`@("`@
M("!T<G5D+G5P9&%T92A[:3H@:7TI"B`@("`@("`@("`@("`@("`@("`@8G)E
M86L*("`@("`@("`@("`@("`@(&X@*ST@,0H@("`@96QS93H*("`@("`@("!P
M<FEN="`G)PH@("`@<F5T=7)N('$L(&0L('-Y;2P@=')U961E<V,*"@ID968@
M9FEN9&ME>7,H:6YP+"!Q+"!D*3H*("`@("(B(D1E=&5R;6EN97,@86YD('!R
M:6YT<R!W:&5T:&5R('1H92!G:79E;B!W;W)D(&ES(&$@:V5Y=V]R9"!O<B!A
M;B!I9"X*("`@($%R9W,Z"B`@("`@("`@:6YP.B!)="!T86ME<R!A('-T<FEN
M9R!A<R!A;B!A<F=U;65N="X*("`@("`@("!Q.B!)="!I<R!A;B!O8FIE8W0@
M;V8@8VQA<W,@475E=64*("`@("`@("!D.B!)="!I<R!A(&1I8W1I;VYA<GD*
M("`@(%)E='5R;G,Z"B`@("`@("`@3F]T:&EN9PH@("`@(B(B"B`@("!G;&]B
M86P@:V5Y=V]R9',L('-Y;0H@("`@:68@:6YP(&EN(&ME>7=O<F1S.@H@("`@
M("`@('$N96YQ=65U92AI;G`I"B`@("`@("`@9"YU<&1A=&4H>VEN<#H@:6YP
M?2D*("`@(&5L<V4Z"B`@("`@("`@='EP92`]('$N:6YD97AE9"@Q*0H@("`@
M("`@('$N96YQ=65U92AI;G`I"B`@("`@("`@9"YU<&1A=&4H>VEN<#H@(FED
M(GTI"B`@("`@("`@:68@:6YP(&YO="!I;B!S>6TN:V5Y<R@I.@H@("`@("`@
H("`@("!S>6TN=7!D871E*'MI;G`Z='EP97TI"B`@("!R971U<FX@9"`@
`
end
SHAR_EOF
  (set 20 16 11 11 20 03 21 'lexical.py'; eval "$shar_touch") &&
  chmod 0644 'lexical.py'
if test $? -ne 0
then ${echo} 'restore of lexical.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'lexical.py: MD5 check failed'
       ) << \SHAR_EOF
148a47ab39fe94bc8b7eba4f5c65797e  lexical.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'lexical.py'` -ne 3325 && \
  ${echo} 'restoration warning:  size of lexical.py is not 3325'
  fi
fi
# ============= makefile ==============
if test -f 'makefile' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING makefile (file already exists)'
else
${echo} 'x - extracting makefile (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'makefile' &&
all:
X	@echo "no makefile necessary, project in python"
SHAR_EOF
  (set 20 16 09 19 10 12 26 'makefile'; eval "$shar_touch") &&
  chmod 0644 'makefile'
if test $? -ne 0
then ${echo} 'restore of makefile failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'makefile: MD5 check failed'
       ) << \SHAR_EOF
55c49ed0a041c39992e694906cfb375e  makefile
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'makefile'` -ne 55 && \
  ${echo} 'restoration warning:  size of makefile is not 55'
  fi
fi
# ============= p3 ==============
if test -f 'p3' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING p3 (file already exists)'
else
${echo} 'x - extracting p3 (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'p3' &&
#!/bin/bash
python f3.py $1
SHAR_EOF
  (set 20 16 11 11 22 36 11 'p3'; eval "$shar_touch") &&
  chmod 0755 'p3'
if test $? -ne 0
then ${echo} 'restore of p3 failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'p3: MD5 check failed'
       ) << \SHAR_EOF
9075b1810e7d4cb519b8370b55fe3761  p3
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'p3'` -ne 28 && \
  ${echo} 'restoration warning:  size of p3 is not 28'
  fi
fi
# ============= parse.py ==============
if test -f 'parse.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING parse.py (file already exists)'
else
${echo} 'x - extracting parse.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 parse.py
M9&5F(&5X:71P9VTH*3H*("`@('!R:6YT("=214I%0U0G"B`@("!E>&ET*"D*
M"@IC;&%S<R!087)S:6YG*&]B:F5C="DZ"B`@("!D968@7U]I;FET7U\H<V5L
M9BP@<2P@9"DZ"B`@("`@("`@<V5L9BYQ(#T@<0H@("`@("`@('-E;&8N9"`]
M(&0*("`@("`@("!S96QF+F9O;&QO=W,@/2![)W!G;2<Z(%LG)"==+`H@("`@
M("`@("`@("`@("`@("`@("`@("`G9"UL:7-T)SH@6R<D)UTL"B`@("`@("`@
M("`@("`@("`@("`@("`@("=!)SH@6R<D)UTL"B`@("`@("`@("`@("`@("`@
M("`@("`@("=D8VQA<G1N)SH@6R=I;G0G+"`G=F]I9"<L("=F;&]A="<L("<D
M)UTL"B`@("`@("`@("`@("`@("`@("`@("`@("=")SH@6R=I;G0G+"`G=F]I
M9"<L("=F;&]A="<L("<D)UTL"B`@("`@("`@("`@("`@("`@("`@("`@("=V
M87(M9&-L87)T;B<Z(%LG.R<L("=;)RP@)VEN="<L("=V;VED)RP@)V9L;V%T
M)RP@)R0G+"`G:60G+"`G*"<L("=N=6TG+"`G=VAI;&4G+"`G>R<L("=I9B<L
M"B`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`G<F5T
M=7)N)UTL"B`@("`@("`@("`@("`@("`@("`@("`@("=F=6XM9&-L87)T;B<Z
M(%LG:6YT)RP@)W9O:60G+"`G9FQO870G+"`G)"==+`H@("`@("`@("`@("`@
M("`@("`@("`@("`G='EP92US<&5C9G(G.B!;)VED)UTL"B`@("`@("`@("`@
M("`@("`@("`@("`@("=P87)A;7,G.B!;)RDG72P*("`@("`@("`@("`@("`@
M("`@("`@("`@)W!A<F%M+6QI<W0G.B!;)RDG72P*("`@("`@("`@("`@("`@
M("`@("`@("`@)T0G.B!;)RDG72P*("`@("`@("`@("`@("`@("`@("`@("`@
M)W!A<F%M)SH@6R<L)RP@)RDG72P*("`@("`@("`@("`@("`@("`@("`@("`@
M)T4G.B!;)RPG+"`G*2==+`H@("`@("`@("`@("`@("`@("`@("`@("`G8V]M
M<&YD+7-T;70G.B!;)V5L<V4G+"`G.R<L("=I9"<L("<H)RP@)VYU;2<L("=W
M:&EL92<L("=[)RP@)VEF)RP@)W)E='5R;B<L("=I;G0G+"`G=F]I9"<L"B`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`G9FQO870G
M+"`G)"<L("=])UTL"B`@("`@("`@("`@("`@("`@("`@("`@("=L;V-A;"UD
M8VQA<G1N)SH@6R<[)RP@)VED)RP@)R@G+"`G;G5M)RP@)W=H:6QE)RP@)WLG
M+"`G:68G+"`G<F5T=7)N)RP@)WTG72P*("`@("`@("`@("`@("`@("`@("`@
M("`@)T8G.B!;)SLG+"`G:60G+"`G*"<L("=N=6TG+"`G=VAI;&4G+"`G>R<L
M("=I9B<L("=R971U<FXG+"`G?2==+`H@("`@("`@("`@("`@("`@("`@("`@
M("`G<W1A=&UN="UL:7-T)SH@6R=])UTL"B`@("`@("`@("`@("`@("`@("`@
M("`@("=')SH@6R=])UTL"B`@("`@("`@("`@("`@("`@("`@("`@("=S=&%T
M;6YT)SH@6R=E;'-E)RP@)SLG+"`G:60G+"`G*"<L("=N=6TG+"`G=VAI;&4G
M+"`G>R<L("=I9B<L("=R971U<FXG+"`G?2==+`H@("`@("`@("`@("`@("`@
M("`@("`@("`G97AP<G-N+7-T;70G.B!;)V5L<V4G+"`G.R<L("=I9"<L("<H
M)RP@)VYU;2<L("=W:&EL92<L("=[)RP@)VEF)RP@)W)E='5R;B<L("=])UTL
M"B`@("`@("`@("`@("`@("`@("`@("`@("=S96QC=&XM<W1M="<Z(%LG96QS
M92<L("<[)RP@)VED)RP@)R@G+"`G;G5M)RP@)W=H:6QE)RP@)WLG+"`G:68G
M+"`G<F5T=7)N)RP@)WTG72P*("`@("`@("`@("`@("`@("`@("`@("`@)T@G
M.B!;)V5L<V4G+"`G.R<L("=I9"<L("<H)RP@)VYU;2<L("=W:&EL92<L("=[
M)RP@)VEF)RP@)W)E='5R;B<L("=])UTL"B`@("`@("`@("`@("`@("`@("`@
M("`@("=I=&5R=&XM<W1M="<Z(%LG96QS92<L("<[)RP@)VED)RP@)R@G+"`G
M;G5M)RP@)W=H:6QE)RP@)WLG+"`G:68G+"`G<F5T=7)N)RP@)WTG72P*("`@
M("`@("`@("`@("`@("`@("`@("`@)W)E=')N+7-T;70G.B!;)V5L<V4G+"`G
M.R<L("=I9"<L("<H)RP@)VYU;2<L("=W:&EL92<L("=[)RP@)VEF)RP@)W)E
M='5R;B<L("=])UTL"B`@("`@("`@("`@("`@("`@("`@("`@("=E>'!R<VXG
M.B!;)RPG+"`G.R<L("==)RP@)RDG72P*("`@("`@("`@("`@("`@("`@("`@
M("`@)W1W;R<Z(%LG+"<L("<[)RP@)UTG+"`G*2==+`H@("`@("`@("`@("`@
M("`@("`@("`@("`G='=O,B<Z(%LG.R<L("==)RP@)RDG72P*("`@("`@("`@
M("`@("`@("`@("`@("`@)W1H<F5E)SH@6R<L)RP@)SLG+"`G72<L("<I)UTL
M"B`@("`@("`@("`@("`@("`@("`@("`@("=T96UP,R<Z(%LG+"<L("<K)RP@
M)RTG+"`G/"<L("<^)RP@)STG+"`G(2<L("<[)RP@)UTG+"`G*2==+`H@("`@
M("`@("`@("`@("`@("`@("`@("`G=&5M<#(G.B!;)RPG+"`G/"<L("<^)RP@
M)STG+"`G(2<L("<[)RP@)UTG+"`G*2==+`H@("`@("`@("`@("`@("`@("`@
M("`@("`G=&5M<"<Z(%LG+"<L("<[)RP@)UTG+"`G*2==+`H@("`@("`@("`@
M("`@("`@("`@("`@("`G<F5L;W`G.B!;)R@G+"`G;G5M)RP@)VED)RP@)RPG
M+"`G.R<L("==)RP@)RDG+"`G*B<L("<O)RP@)RLG+"`G+2<L("<\)RP@)SXG
M+"`G/2<L("<A)UTL"B`@("`@("`@("`@("`@("`@("`@("`@("=,)SH@6R<H
M)RP@)VYU;2<L("=I9"==+`H@("`@("`@("`@("`@("`@("`@("`@("`G861D
M+65X<')S;B<Z(%LG/"<L("<^)RP@)STG+"`G(2<L("<[)RP@)UTG+"`G*2==
M+`H@("`@("`@("`@("`@("`@("`@("`@("`G861D;W`G.B!;)R@G+"`G:60G
M+"`G;G5M)UTL"B`@("`@("`@("`@("`@("`@("`@("`@("=T97)M)SH@6R<K
M)RP@)RTG+"`G/"<L("<^)RP@)STG+"`G(2<L("<[)RP@)UTG+"`G*2==+`H@
M("`@("`@("`@("`@("`@("`@("`@("`G;75L;W`G.B!;)R@G+"`G:60G+"`G
M;G5M)UTL"B`@("`@("`@("`@("`@("`@("`@("`@("=F86-T;W(G.B!;)RHG
M+"`G+R<L("<K)RP@)RTG+"`G/"<L("<^)RP@)STG+"`G(2<L("<[)RP@)UTG
M+"`G*2==+`H@("`@("`@("`@("`@("`@("`@("`@("`G;VYE)SH@6R<J)RP@
M)R\G+"`G*R<L("<M)RP@)SPG+"`G/B<L("<])RP@)R$G+"`G.R<L("==)RP@
M)RDG72P*("`@("`@("`@("`@("`@("`@("`@("`@)V%R9W,G.B!;)RDG72P*
M("`@("`@("`@("`@("`@("`@("`@("`@)V%R9RUL:7-T)SH@6R<I)UTL"B`@
M("`@("`@("`@("`@("`@("`@("`@("=/)SH@6R<I)UU]"B`@("`@("`@<V5L
M9BYF:7)S=',@/2![)W!G;2<Z(%LG:6YT)RP@)W9O:60G+"`G9FQO870G72P*
M("`@("`@("`@("`@("`@("`@("`@("`G9"UL:7-T)SH@6R=I;G0G+"`G=F]I
M9"<L("=F;&]A="==+`H@("`@("`@("`@("`@("`@("`@("`@("=!)SH@6R<G
M+"`G:6YT)RP@)W9O:60G+"`G9FQO870G72P*("`@("`@("`@("`@("`@("`@
M("`@("`G9&-L87)T;B<Z(%LG:6YT)RP@)W9O:60G+"`G9FQO870G72P*("`@
M("`@("`@("`@("`@("`@("`@("`G0B<Z(%LG.R<L("=;)RP@)R@G72P*("`@
M("`@("`@("`@("`@("`@("`@("`G=F%R+61C;&%R=&XG.B!;)SLG+"`G6R==
M+`H@("`@("`@("`@("`@("`@("`@("`@("=F=6XM9&-L87)T;B<Z(%LG*"==
M+`H@("`@("`@("`@("`@("`@("`@("`@("=T>7!E+7-P96-F<B<Z(%LG:6YT
M)RP@)W9O:60G+"`G9FQO870G72P*("`@("`@("`@("`@("`@("`@("`@("`G
M<&%R86US)SH@6R=V;VED)RP@)VEN="<L("=F;&]A="==+`H@("`@("`@("`@
M("`@("`@("`@("`@("=P87)A;2UL:7-T)SH@6R=I;G0G+"`G=F]I9"<L("=F
M;&]A="==+`H@("`@("`@("`@("`@("`@("`@("`@("=$)SH@6R<L)RP@)R==
M+`H@("`@("`@("`@("`@("`@("`@("`@("=P87)A;2<Z(%LG:6YT)RP@)W9O
M:60G+"`G9FQO870G72P*("`@("`@("`@("`@("`@("`@("`@("`G12<Z(%LG
M6R<L("<G72P*("`@("`@("`@("`@("`@("`@("`@("`G8V]M<&YD+7-T;70G
M.B!;)WLG72P*("`@("`@("`@("`@("`@("`@("`@("`G;&]C86PM9&-L87)T
M;B<Z(%LG)RP@)SLG+"`G6R==+`H@("`@("`@("`@("`@("`@("`@("`@("=&
M)SH@6R=I;G0G+"`G9FQO870G72P*("`@("`@("`@("`@("`@("`@("`@("`G
M<W1A=&UN="UL:7-T)SH@6R<G+"`G.R<L("=I9"<L("<H)RP@)VYU;2<L("=W
M:&EL92<L("=[)RP@)VEF)RP@)W)E='5R;B==+`H@("`@("`@("`@("`@("`@
M("`@("`@("=')SH@6R<G+"`G.R<L("=I9"<L("<H)RP@)VYU;2<L("=W:&EL
M92<L("=[)RP@)VEF)RP@)W)E='5R;B==+`H@("`@("`@("`@("`@("`@("`@
M("`@("=S=&%T;6YT)SH@6R<[)RP@)VED)RP@)R@G+"`G;G5M)RP@)W=H:6QE
M)RP@)WLG+"`G:68G+"`G<F5T=7)N)UTL"B`@("`@("`@("`@("`@("`@("`@
M("`@)V5X<')S;BUS=&UT)SH@6R<[)RP@)VED)RP@)R@G+"`G;G5M)UTL"B`@
M("`@("`@("`@("`@("`@("`@("`@)W-E;&-T;BUS=&UT)SH@6R=I9B==+`H@
M("`@("`@("`@("`@("`@("`@("`@("=()SH@6R=E;'-E)RP@)R==+`H@("`@
M("`@("`@("`@("`@("`@("`@("=I=&5R=&XM<W1M="<Z(%LG=VAI;&4G72P*
M("`@("`@("`@("`@("`@("`@("`@("`G<F5T<FXM<W1M="<Z(%LG<F5T=7)N
M)UTL"B`@("`@("`@("`@("`@("`@("`@("`@)V5X<')S;B<Z(%LG:60G+"`G
M*"<L("=N=6TG72P*("`@("`@("`@("`@("`@("`@("`@("`G='=O)SH@6R<G
M+"`G/2<L("=;)RP@)R@G72P*("`@("`@("`@("`@("`@("`@("`@("`G='=O
M,B<Z(%LG)RP@)RHG+"`G+R<L("<K)RP@)RTG+"`G/"<L("<^)RP@)STG+"`G
M(2==+`H@("`@("`@("`@("`@("`@("`@("`@("=T:')E92<Z(%LG)RP@)RHG
M+"`G+R<L("<K)RP@)RTG+"`G/"<L("<^)RP@)STG+"`G(2==+`H@("`@("`@
M("`@("`@("`@("`@("`@("=T96UP,R<Z(%LG)RP@)RHG+"`G+R==+`H@("`@
M("`@("`@("`@("`@("`@("`@("=T96UP,B<Z(%LG)RP@)RLG+"`G+2==+`H@
M("`@("`@("`@("`@("`@("`@("`@("=T96UP)SH@6R<G+"`G/"<L("<^)RP@
M)STG+"`G(2==+`H@("`@("`@("`@("`@("`@("`@("`@("=R96QO<"<Z(%LG
M/"<L("<^)RP@)STG+"`G(2==+`H@("`@("`@("`@("`@("`@("`@("`@("=,
M)SH@6R<])RP@)R==+`H@("`@("`@("`@("`@("`@("`@("`@("=A9&0M97AP
M<G-N)SH@6R<H)RP@)VED)RP@)VYU;2==+`H@("`@("`@("`@("`@("`@("`@
M("`@("=A9&1O<"<Z(%LG*R<L("<M)UTL"B`@("`@("`@("`@("`@("`@("`@
M("`@)W1E<FTG.B!;)R@G+"`G:60G+"`G;G5M)UTL"B`@("`@("`@("`@("`@
M("`@("`@("`@)VUU;&]P)SH@6R<J)RP@)R\G72P*("`@("`@("`@("`@("`@
M("`@("`@("`G9F%C=&]R)SH@6R<H)RP@)VED)RP@)VYU;2==+`H@("`@("`@
M("`@("`@("`@("`@("`@("=O;F4G.B!;)ULG+"`G)UTL"B`@("`@("`@("`@
M("`@("`@("`@("`@)V%R9W,G.B!;)R<L("<H)RP@)VYU;2<L("=I9"==+`H@
M("`@("`@("`@("`@("`@("`@("`@("=A<F<M;&ES="<Z(%LG*"<L("=N=6TG
M+"`G:60G72P*("`@("`@("`@("`@("`@("`@("`@("`G3R<Z(%LG+"<L("<G
M77T*("`@("`@("!S96QF+FD@/2!S96QF+G$N<VEZ92@I"B`@("`@("`@<V5L
M9BYT97)M<R`](%LG:60G+"`G.R<L("=;)RP@)VYU;2<L("==)RP@)R@G+"`G
M*2<L("=I;G0G+"`G=F]I9"<L("=F;&]A="<L("<L)RP@)WLG+"`G?2<L("=I
M9B<L("=E;'-E)RP*("`@("`@("`@("`@("`@("`@("`@("=W:&EL92<L("=R
M971U<FXG+"`G/2<L("<\)RP@)SXG+"`G(2<L("<K)RP@)RTG+"`G*B<L("<O
M)UT*"B`@("!D968@<W1A<G0H<V5L9BDZ"B`@("`@("`@<F5T=7)N('-E;&8N
M<&=M*'-E;&8N<2YS:7IE*"DI"@H@("`@9&5F(&=E=&9I<G-T*'-E;&8L(&YO
M;G1E<FTI.@H@("`@("`@(')E='5R;B!S96QF+F9I<G-T<UMN;VYT97)M70H*
M("`@(&1E9B!G971F;VQL;W<H<V5L9BP@;F]N=&5R;2DZ"B`@("`@("`@<F5T
M=7)N('-E;&8N9F]L;&]W<UMN;VYT97)M70H*("`@(&1E9B!N="AS96QF+"!N
M*3H*("`@("`@("!G971I9"`]('-E;&8N<2YI;F1E>&5D*&XI"B`@("`@("`@
M<F5T=7)N('-E;&8N9%MG971I9%T*"B`@("!D968@86-C97!T*'-E;&8L(',L
M(&$I.@H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@<SH*("`@("`@("`@("`@
M(R!P<FEN="=A8V-E<'1E9#HG+"!S96QF+FYT*&$I"B`@("`@("`@("`@(')E
M='5R;B!A("T@,0H@("`@("`@(&5L<V4Z"B`@("`@("`@("`@(&5X:71P9VTH
M*0H*("`@(&1E9B!P9VTH<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN="AA
M*2`]/2`G)"<Z"B`@("`@("`@("`@(')E='5R;B!4<G5E"B`@("`@("`@96QS
M93H*("`@("`@("`@("`@8B`]('-E;&8N9%]L:7-T*&$I"B`@("`@("`@("`@
M(&EF(&(@/3T@,3H*("`@("`@("`@("`@("`@(')E='5R;B!4<G5E"B`@("`@
M("`@("`@(&5L<V4Z"B`@("`@("`@("`@("`@("!E>&ET<&=M*"D*"B`@("!D
M968@9%]L:7-T*'-E;&8L(&$I.@H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@
M<V5L9BYG971F:7)S="@G9&-L87)T;B<I.@H@("`@("`@("`@("!B(#T@<V5L
M9BYD8VQA<G1N*&$I"B`@("`@("`@("`@(')E='5R;B!S96QF+D$H8BD*("`@
M("`@("!E;'-E.@H@("`@("`@("`@("!E>&ET<&=M*"D*"B`@("!D968@02AS
M96QF+"!A*3H*("`@("`@("!I9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9F]L
M;&]W*"=!)RDZ"B`@("`@("`@("`@(')E='5R;B!A"B`@("`@("`@96QI9B!S
M96QF+FYT*&$I(&EN('-E;&8N9V5T9FER<W0H)V1C;&%R=&XG*3H*("`@("`@
M("`@("`@8B`]('-E;&8N9&-L87)T;BAA*0H@("`@("`@("`@("!R971U<FX@
M<V5L9BY!*&(I"B`@("`@("`@96QS93H*("`@("`@("`@("`@97AI='!G;2@I
M"@H@("`@9&5F(&1C;&%R=&XH<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN
M="AA*2`]/2`G=F]I9"<Z"B`@("`@("`@("`@(&(@/2!S96QF+F%C8V5P="@G
M=F]I9"<L(&$I"B`@("`@("`@("`@(&,@/2!S96QF+F%C8V5P="@G:60G+"!B
M*0H@("`@("`@("`@("!R971U<FX@<V5L9BYF=6Y?9&-L87)T;BAC*0H@("`@
M("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=T>7!E+7-P
M96-F<B<I.@H@("`@("`@("`@("!B(#T@<V5L9BYT>7!E7W-P96-F<BAA*0H@
M("`@("`@("`@("!C(#T@<V5L9BYA8V-E<'0H)VED)RP@8BD*("`@("`@("`@
M("`@<F5T=7)N('-E;&8N0BAC*0H@("`@("`@(&5L<V4Z"B`@("`@("`@("`@
M(&5X:71P9VTH*0H*("`@(&1E9B!"*'-E;&8L(&$I.@H@("`@("`@(&EF('-E
M;&8N;G0H82D@:6X@<V5L9BYG971F:7)S="@G=F%R+61C;&%R=&XG*3H*("`@
M("`@("`@("`@<F5T=7)N('-E;&8N=F%R7V1C;&%R=&XH82D*("`@("`@("!E
M;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F:7)S="@G9G5N+61C;&%R=&XG
M*3H*("`@("`@("`@("`@<F5T=7)N('-E;&8N9G5N7V1C;&%R=&XH82D*("`@
M("`@("!E;'-E.@H@("`@("`@("`@("!E>&ET<&=M*"D*"B`@("!D968@='EP
M95]S<&5C9G(H<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN="AA*2`]/2`G
M:6YT)SH*("`@("`@("`@("`@<F5T=7)N('-E;&8N86-C97!T*"=I;G0G+"!A
M*0H@("`@("`@(&5L:68@<V5L9BYN="AA*2`]/2`G9FQO870G.@H@("`@("`@
M("`@("!R971U<FX@<V5L9BYA8V-E<'0H)V9L;V%T)RP@82D*("`@("`@("!E
M;&EF('-E;&8N;G0H82D@/3T@)W9O:60G.@H@("`@("`@("`@("!R971U<FX@
M<V5L9BYA8V-E<'0H)W9O:60G+"!A*0H@("`@("`@(&5L<V4Z"B`@("`@("`@
M("`@(&5X:71P9VTH*0H*("`@(&1E9B!V87)?9&-L87)T;BAS96QF+"!A*3H*
M("`@("`@("!I9B!S96QF+FYT*&$I(#T]("<[)SH*("`@("`@("`@("`@<F5T
M=7)N('-E;&8N86-C97!T*"<[)RP@82D*("`@("`@("!E;&EF('-E;&8N;G0H
M82D@/3T@)ULG.@H@("`@("`@("`@("!B(#T@<V5L9BYA8V-E<'0H)ULG+"!A
M*0H@("`@("`@("`@("!C(#T@<V5L9BYA8V-E<'0H)VYU;2<L(&(I"B`@("`@
M("`@("`@(&0@/2!S96QF+F%C8V5P="@G72<L(&,I"B`@("`@("`@("`@(')E
M='5R;B!S96QF+F%C8V5P="@G.R<L(&0I"B`@("`@("`@96QS93H*("`@("`@
M("`@("`@97AI='!G;2@I"@H@("`@9&5F(&9U;E]D8VQA<G1N*'-E;&8L(&$I
M.@H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@6R<H)UTZ"B`@("`@("`@("`@
M(&(@/2!S96QF+F%C8V5P="@G*"<L(&$I"B`@("`@("`@("`@(&,@/2!S96QF
M+G!A<F%M<RAB*0H@("`@("`@("`@("!D(#T@<V5L9BYA8V-E<'0H)RDG+"!C
M*0H@("`@("`@("`@("!R971U<FX@<V5L9BYC;VUP;F1?<W1M="AD*0H@("`@
M("`@(&5L<V4Z"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(&1E9B!P87)A
M;7,H<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN="AA*2`]/2`G=F]I9"<Z
M"B`@("`@("`@("`@(')E='5R;B!S96QF+F%C8V5P="@G=F]I9"<L(&$I"B`@
M("`@("`@96QI9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9FER<W0H)W!A<F%M
M+6QI<W0G*3H*("`@("`@("`@("`@<F5T=7)N('-E;&8N<&%R86U?;&ES="AA
M*0H@("`@("`@(&5L<V4Z"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(&1E
M9B!P87)A;5]L:7-T*'-E;&8L(&$I.@H@("`@("`@(&EF('-E;&8N;G0H82D@
M:6X@<V5L9BYG971F:7)S="@G<&%R86TG*3H*("`@("`@("`@("`@8B`]('-E
M;&8N<&%R86TH82D*("`@("`@("`@("`@<F5T=7)N('-E;&8N1"AB*0H@("`@
M("`@(&5L<V4Z"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(&1E9B!$*'-E
M;&8L(&$I.@H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@6R<L)UTZ"B`@("`@
M("`@("`@(&(@/2!S96QF+F%C8V5P="@G+"<L(&$I"B`@("`@("`@("`@(&,@
M/2!S96QF+G!A<F%M*&(I"B`@("`@("`@("`@(&0@/2!S96QF+D0H8RD*("`@
M("`@("`@("`@<F5T=7)N(&0*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@
M<V5L9BYG971F;VQL;W<H)T0G*3H*("`@("`@("`@("`@<F5T=7)N(&$*("`@
M("`@("!E;'-E.@H@("`@("`@("`@("!E>&ET<&=M*"D*"B`@("!D968@<&%R
M86TH<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN="AA*2!I;B!S96QF+F=E
M=&9I<G-T*"=T>7!E+7-P96-F<B<I.@H@("`@("`@("`@("!B(#T@<V5L9BYT
M>7!E7W-P96-F<BAA*0H@("`@("`@("`@("!C(#T@<V5L9BYA8V-E<'0H)VED
M)RP@8BD*("`@("`@("`@("`@<F5T=7)N('-E;&8N12AC*0H@("`@("`@(&5L
M<V4Z"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(&1E9B!%*'-E;&8L(&$I
M.@H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@6R=;)UTZ"B`@("`@("`@("`@
M(&(@/2!S96QF+F%C8V5P="@G6R<L(&$I"B`@("`@("`@("`@(')E='5R;B!S
M96QF+F%C8V5P="@G72<L(&(I"B`@("`@("`@96QI9B!S96QF+FYT*&$I(&EN
M('-E;&8N9V5T9F]L;&]W*"=%)RDZ"B`@("`@("`@("`@(')E='5R;B!A"B`@
M("`@("`@96QS93H*("`@("`@("`@("`@97AI='!G;2@I"@H@("`@9&5F(&-O
M;7!N9%]S=&UT*'-E;&8L(&$I.@H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@
M<V5L9BYG971F:7)S="@G8V]M<&YD+7-T;70G*3H*("`@("`@("`@("`@8B`]
M('-E;&8N86-C97!T*"=[)RP@82D*("`@("`@("`@("`@8R`]('-E;&8N;&]C
M86Q?9&-L87)T;BAB*0H@("`@("`@("`@("!D(#T@<V5L9BYS=&%T;6YT7VQI
M<W0H8RD*("`@("`@("`@("`@<F5T=7)N('-E;&8N86-C97!T*"=])RP@9"D*
M("`@("`@("!E;'-E.@H@("`@("`@("`@("!E>&ET<&=M*"D*"B`@("!D968@
M;&]C86Q?9&-L87)T;BAS96QF+"!A*3H*("`@("`@("!I9B!S96QF+FYT*&$I
M(&EN('-E;&8N9V5T9FER<W0H)T8G*3H*("`@("`@("`@("`@<F5T=7)N('-E
M;&8N1BAA*0H@("`@("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9O
M;&QO=R@G;&]C86PM9&-L87)T;B<I.@H@("`@("`@("`@("!R971U<FX@80H@
M("`@("`@(&5L<V4Z"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(&1E9B!&
M*'-E;&8L(&$I.@H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@6R=I;G0G+"`G
M9FQO870G73H*("`@("`@("`@("`@8B`]('-E;&8N='EP95]S<&5C9G(H82D*
M("`@("`@("`@("`@8R`]('-E;&8N86-C97!T*"=I9"<L(&(I"B`@("`@("`@
M("`@(&0@/2!S96QF+G9A<E]D8VQA<G1N*&,I"B`@("`@("`@("`@(')E='5R
M;B!S96QF+D8H9"D*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG
M971F;VQL;W<H)T8G*3H*("`@("`@("`@("`@<F5T=7)N(&$*("`@("`@("!E
M;'-E.@H@("`@("`@("`@("!E>&ET<&=M*"D*"B`@("!D968@<W1A=&UN=%]L
M:7-T*'-E;&8L(&$I.@H@("`@("`@(')E='5R;B!S96QF+D<H82D*"B`@("!D
M968@1RAS96QF+"!A*3H*("`@("`@("!I9B!S96QF+FYT*&$I(&EN('-E;&8N
M9V5T9FER<W0H)W-T871M;G0G*3H*("`@("`@("`@("`@8B`]('-E;&8N<W1A
M=&UN="AA*0H@("`@("`@("`@("!R971U<FX@<V5L9BY'*&(I"B`@("`@("`@
M96QI9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9F]L;&]W*"=')RDZ"B`@("`@
M("`@("`@(')E='5R;B!A"B`@("`@("`@96QS93H*("`@("`@("`@("`@97AI
M='!G;2@I"@H@("`@9&5F('-T871M;G0H<V5L9BP@82DZ"B`@("`@("`@:68@
M<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=E>'!R<VXM<W1M="<I.@H@
M("`@("`@("`@("!R971U<FX@<V5L9BYE>'!R<VY?<W1M="AA*0H@("`@("`@
M(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=S96QC=&XM<W1M
M="<I.@H@("`@("`@("`@("!R971U<FX@<V5L9BYS96QC=&Y?<W1M="AA*0H@
M("`@("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=I=&5R
M=&XM<W1M="<I.@H@("`@("`@("`@("!R971U<FX@<V5L9BYI=&5R=&Y?<W1M
M="AA*0H@("`@("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T
M*"=R971R;BUS=&UT)RDZ"B`@("`@("`@("`@(')E='5R;B!S96QF+G)E=')N
M7W-T;70H82D*("`@("`@("!E;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F
M:7)S="@G8V]M<&YD+7-T;70G*3H*("`@("`@("`@("`@<F5T=7)N('-E;&8N
M8V]M<&YD7W-T;70H82D*("`@("`@("!E;'-E.@H@("`@("`@("`@("!E>&ET
M<&=M*"D*"B`@("!D968@97AP<G-N7W-T;70H<V5L9BP@82DZ"B`@("`@("`@
M:68@<V5L9BYN="AA*2`]/2`G.R<Z"B`@("`@("`@("`@(')E='5R;B!S96QF
M+F%C8V5P="@G.R<L(&$I"B`@("`@("`@96QI9B!S96QF+FYT*&$I(&EN('-E
M;&8N9V5T9FER<W0H)V5X<')S;B<I.@H@("`@("`@("`@("!B(#T@<V5L9BYE
M>'!R<VXH82D*("`@("`@("`@("`@<F5T=7)N('-E;&8N86-C97!T*"<[)RP@
M8BD*("`@("`@("!E;'-E.@H@("`@("`@("`@("!E>&ET<&=M*"D*"B`@("!D
M968@<V5L8W1N7W-T;70H<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN="AA
M*2`]/2`G:68G.@H@("`@("`@("`@("!B(#T@<V5L9BYA8V-E<'0H)VEF)RP@
M82D*("`@("`@("`@("`@8R`]('-E;&8N86-C97!T*"<H)RP@8BD*("`@("`@
M("`@("`@9"`]('-E;&8N97AP<G-N*&,I"B`@("`@("`@("`@(&4@/2!S96QF
M+F%C8V5P="@G*2<L(&0I"B`@("`@("`@("`@(&8@/2!S96QF+G-T871M;G0H
M92D*("`@("`@("`@("`@<F5T=7)N('-E;&8N2"AF*0H@("`@("`@(&5L<V4Z
M"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(&1E9B!(*'-E;&8L(&$I.@H@
M("`@("`@(&EF('-E;&8N;G0H82D@/3T@)V5L<V4G.@H@("`@("`@("`@("!B
M(#T@<V5L9BYA8V-E<'0H)V5L<V4G+"!A*0H@("`@("`@("`@("!R971U<FX@
M<V5L9BYS=&%T;6YT*&(I"B`@("`@("`@96QI9B!S96QF+FYT*&$I(&EN('-E
M;&8N9V5T9F]L;&]W*"=()RDZ"B`@("`@("`@("`@(')E='5R;B!A"B`@("`@
M("`@96QS93H*("`@("`@("`@("`@97AI='!G;2@I"@H@("`@9&5F(&ET97)T
M;E]S=&UT*'-E;&8L(&$I.@H@("`@("`@(&EF('-E;&8N;G0H82D@/3T@)W=H
M:6QE)SH*("`@("`@("`@("`@8B`]('-E;&8N86-C97!T*"=W:&EL92<L(&$I
M"B`@("`@("`@("`@(&,@/2!S96QF+F%C8V5P="@G*"<L(&(I"B`@("`@("`@
M("`@(&0@/2!S96QF+F5X<')S;BAC*0H@("`@("`@("`@("!E(#T@<V5L9BYA
M8V-E<'0H)RDG+"!D*0H@("`@("`@("`@("!R971U<FX@<V5L9BYS=&%T;6YT
M*&4I"B`@("`@("`@96QS93H*("`@("`@("`@("`@97AI='!G;2@I"@H@("`@
M9&5F(')E=')N7W-T;70H<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN="AA
M*2`]/2`G<F5T=7)N)SH*("`@("`@("`@("`@8B`]('-E;&8N86-C97!T*"=R
M971U<FXG+"!A*0H@("`@("`@("`@("!R971U<FX@<V5L9BYE>'!R<VY?<W1M
M="AB*0H@("`@("`@(&5L<V4Z"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@
M(",@0TA!3D=%4R!35$%25%,@2$5210H*("`@(&1E9B!E>'!R<VXH<V5L9BP@
M82DZ"B`@("`@("`@:68@<V5L9BYN="AA*2`]/2`G*"<Z"B`@("`@("`@("`@
M(&(@/2!S96QF+F%C8V5P="@G*"<L(&$I"B`@("`@("`@("`@(&,@/2!S96QF
M+F5X<')S;BAB*0H@("`@("`@("`@("!D(#T@<V5L9BYA8V-E<'0H)RDG+"!C
M*0H@("`@("`@("`@("!R971U<FX@<V5L9BYT:')E92AD*0H@("`@("`@(&5L
M:68@<V5L9BYN="AA*2`]/2`G;G5M)SH*("`@("`@("`@("`@8B`]('-E;&8N
M86-C97!T*"=N=6TG+"!A*0H@("`@("`@("`@("!R971U<FX@<V5L9BYT:')E
M92AB*0H@("`@("`@(&5L:68@<V5L9BYN="AA*2`]/2`G:60G.@H@("`@("`@
M("`@("!B(#T@<V5L9BYA8V-E<'0H)VED)RP@82D*("`@("`@("`@("`@<F5T
M=7)N('-E;&8N='=O*&(I"B`@("`@("`@96QS93H*("`@("`@("`@("`@97AI
M='!G;2@I"@H@("`@9&5F('1W;RAS96QF+"!A*3H*("`@("`@("!I9B!S96QF
M+FYT*&$I(&EN('-E;&8N9V5T9FER<W0H)V]N92<I("L@6R<])UTZ"B`@("`@
M("`@("`@(&(@/2!S96QF+F]N92AA*0H@("`@("`@("`@("!C(#T@<V5L9BYR
M96QO<"AB*0H@("`@("`@("`@("!R971U<FX@<V5L9BYT=V\R*&,I"B`@("`@
M("`@96QI9B!S96QF+FYT*&$I(#T]("<H)SH*("`@("`@("`@("`@8B`]('-E
M;&8N86-C97!T*"<H)RP@82D*("`@("`@("`@("`@8R`]('-E;&8N87)G<RAB
M*0H@("`@("`@("`@("!D(#T@<V5L9BYA8V-E<'0H)RDG+"!C*0H@("`@("`@
M("`@("!R971U<FX@<V5L9BYT:')E92AD*0H@("`@("`@(&5L:68@<V5L9BYN
M="AA*2!I;B!S96QF+F=E=&9I<G-T*"=T:')E92<I*W-E;&8N9V5T9F]L;&]W
M*"=T=V\G*3H*("`@("`@("`@("`@<F5T=7)N('-E;&8N=&AR964H82D*("`@
M("`@("!E;'-E.@H@("`@("`@("`@("!E>&ET<&=M*"D*"B`@("!D968@=&AR
M964H<V5L9BP@82DZ"B`@("`@("`@8B`]('-E;&8N=&5M<#,H82D*("`@("`@
M("!C(#T@<V5L9BYT96UP,BAB*0H@("`@("`@(')E='5R;B!S96QF+G1E;7`H
M8RD*"B`@("!D968@=&5M<#,H<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN
M="AA*2!I;B!S96QF+F=E=&9I<G-T*"=M=6QO<"<I.@H@("`@("`@("`@("!B
M(#T@<V5L9BYM=6QO<"AA*0H@("`@("`@("`@("!C(#T@<V5L9BYF86-T;W(H
M8BD*("`@("`@("`@("`@<F5T=7)N('-E;&8N=&5M<#,H8RD*("`@("`@("!E
M;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F;VQL;W<H)W1E;7`S)RDZ"B`@
M("`@("`@("`@(')E='5R;B!A"B`@("`@("`@96QS93H*("`@("`@("`@("`@
M97AI='!G;2@I"@H@("`@9&5F('1E;7`R*'-E;&8L(&$I.@H@("`@("`@(&EF
M('-E;&8N;G0H82D@:6X@<V5L9BYG971F:7)S="@G861D;W`G*3H*("`@("`@
M("`@("`@8B`]('-E;&8N861D;W`H82D*("`@("`@("`@("`@8R`]('-E;&8N
M=&5R;2AB*0H@("`@("`@("`@("!R971U<FX@<V5L9BYT96UP,BAC*0H@("`@
M("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9O;&QO=R@G=&5M<#(G
M*3H*("`@("`@("`@("`@<F5T=7)N(&$*("`@("`@("!E;'-E.@H@("`@("`@
M("`@("!E>&ET<&=M*"D*"B`@("!D968@=&5M<"AS96QF+"!A*3H*("`@("`@
M("!I9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9FER<W0H)W)E;&]P)RDZ"B`@
M("`@("`@("`@(&(@/2!S96QF+G)E;&]P*&$I"B`@("`@("`@("`@(&,@/2!S
M96QF+F%D9%]E>'!R<VXH8BD*("`@("`@("`@("`@<F5T=7)N('-E;&8N=&5M
M<"AC*0H@("`@("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9O;&QO
M=R@G=&5M<"<I.@H@("`@("`@("`@("!R971U<FX@80H@("`@("`@(&5L<V4Z
M"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(&1E9B!T=V\R*'-E;&8L(&$I
M.@H@("`@("`@(&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F:7)S="@G=&AR
M964G*3H*("`@("`@("`@("`@<F5T=7)N('-E;&8N=&AR964H82D*("`@("`@
M("!E;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F:7)S="@G97AP<G-N)RDZ
M"B`@("`@("`@("`@(')E='5R;B!S96QF+F5X<')S;BAA*0H@("`@("`@(&5L
M:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9O;&QO=R@G='=O,B<I.@H@("`@
M("`@("`@("!R971U<FX@80H@("`@("`@(&5L<V4Z"B`@("`@("`@("`@(&5X
M:71P9VTH*0H*("`@(&1E9B!R96QO<"AS96QF+"!A*3H*("`@("`@("!I9B!S
M96QF+FYT*&$I(#T]("<\)SH*("`@("`@("`@("`@8B`]('-E;&8N86-C97!T
M*"<\)RP@82D*("`@("`@("`@("`@<F5T=7)N('-E;&8N3"AB*0H@("`@("`@
M(&5L:68@<V5L9BYN="AA*2`]/2`G/B<Z"B`@("`@("`@("`@(&,@/2!S96QF
M+F%C8V5P="@G/B<L(&$I"B`@("`@("`@("`@(')E='5R;B!S96QF+DPH8RD*
M("`@("`@("!E;&EF('-E;&8N;G0H82D@/3T@)STG.@H@("`@("`@("`@("!D
M(#T@<V5L9BYA8V-E<'0H)STG+"!A*0H@("`@("`@("`@("!R971U<FX@<V5L
M9BY,*&0I"B`@("`@("`@96QI9B!S96QF+FYT*&$I(#T]("<A)SH*("`@("`@
M("`@("`@92`]('-E;&8N86-C97!T*"<A)RP@82D*("`@("`@("`@("`@<F5T
M=7)N('-E;&8N86-C97!T*"<])RP@92D*("`@("`@("!E;&EF('-E;&8N;G0H
M82D@:6X@<V5L9BYG971F;VQL;W<H)W)E;&]P)RDZ"B`@("`@("`@("`@(')E
M='5R;B!A"B`@("`@("`@96QS93H*("`@("`@("`@("`@97AI='!G;2@I"@H@
M("`@(R!K97!T('-A;64*("`@(&1E9B!,*'-E;&8L(&$I.@H@("`@("`@(&EF
M('-E;&8N;G0H82D@/3T@)STG.@H@("`@("`@("`@("!R971U<FX@<V5L9BYA
M8V-E<'0H)STG+"!A*0H@("`@("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF
M+F=E=&9O;&QO=R@G3"<I.@H@("`@("`@("`@("!R971U<FX@80H@("`@("`@
M(&5L<V4Z"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(",@8VAA;F=E9`H@
M("`@9&5F(&%D9%]E>'!R<VXH<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN
M="AA*2!I;B!S96QF+F=E=&9I<G-T*"=T97)M)RDZ"B`@("`@("`@("`@(&(@
M/2!S96QF+G1E<FTH82D*("`@("`@("`@("`@<F5T=7)N('-E;&8N=&5M<#(H
M8BD*("`@("`@("!E;'-E.@H@("`@("`@("`@("!E>&ET<&=M*"D*"B`@("`C
M('-A;64*("`@(&1E9B!A9&1O<"AS96QF+"!A*3H*("`@("`@("!I9B!S96QF
M+FYT*&$I(#T]("<K)SH*("`@("`@("`@("`@<F5T=7)N('-E;&8N86-C97!T
M*"<K)RP@82D*("`@("`@("!E;&EF('-E;&8N;G0H82D@/3T@)RTG.@H@("`@
M("`@("`@("!R971U<FX@<V5L9BYA8V-E<'0H)RTG+"!A*0H@("`@("`@(&5L
M<V4Z"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(",@8VAA;F=E9`H@("`@
M9&5F('1E<FTH<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN="AA*2!I;B!S
M96QF+F=E=&9I<G-T*"=F86-T;W(G*3H*("`@("`@("`@("`@8B`]('-E;&8N
M9F%C=&]R*&$I"B`@("`@("`@("`@(')E='5R;B!S96QF+G1E;7`S*&(I"B`@
M("`@("`@96QS93H*("`@("`@("`@("`@97AI='!G;2@I"@H@("`@(R!S86UE
M"B`@("!D968@;75L;W`H<V5L9BP@82DZ"B`@("`@("`@:68@<V5L9BYN="AA
M*2!I;B!;)RHG73H*("`@("`@("`@("`@<F5T=7)N('-E;&8N86-C97!T*"<J
M)RP@82D*("`@("`@("!I9B!S96QF+FYT*&$I(&EN(%LG+R==.@H@("`@("`@
M("`@("!R971U<FX@<V5L9BYA8V-E<'0H)R\G+"!A*0H@("`@("`@(&5L<V4Z
M"B`@("`@("`@("`@(&5X:71P9VTH*0H*("`@(",@8VAA;F=E9`H@("`@9&5F
M(&9A8W1O<BAS96QF+"!A*3H*("`@("`@("!I9B!S96QF+FYT*&$I(&EN(%LG
M*"==.@H@("`@("`@("`@("!B(#T@<V5L9BYA8V-E<'0H)R@G+"!A*0H@("`@
M("`@("`@("!C(#T@<V5L9BYE>'!R<VXH8BD*("`@("`@("`@("`@<F5T=7)N
M('-E;&8N86-C97!T*"<I)RP@8RD*("`@("`@("!E;&EF('-E;&8N;G0H82D@
M:6X@6R=I9"==.@H@("`@("`@("`@("!D(#T@<V5L9BYA8V-E<'0H)VED)RP@
M82D*("`@("`@("`@("`@<F5T=7)N('-E;&8N;VYE*&0I"B`@("`@("`@96QI
M9B!S96QF+FYT*&$I(&EN(%LG;G5M)UTZ"B`@("`@("`@("`@(')E='5R;B!S
M96QF+F%C8V5P="@G;G5M)RP@82D*("`@("`@("!E;'-E.@H@("`@("`@("`@
M("!E>&ET<&=M*"D*"B`@("!D968@;VYE*'-E;&8L(&$I.@H@("`@("`@(&EF
M('-E;&8N;G0H82D@/3T@)ULG.@H@("`@("`@("`@("!B(#T@<V5L9BYA8V-E
M<'0H)ULG+"!A*0H@("`@("`@("`@("!C(#T@<V5L9BYE>'!R<VXH8BD*("`@
M("`@("`@("`@<F5T=7)N('-E;&8N86-C97!T*"==)RP@8RD*("`@("`@("!E
M;&EF('-E;&8N;G0H82D@:6X@<V5L9BYG971F;VQL;W<H)V]N92<I.@H@("`@
M("`@("`@("!R971U<FX@80H@("`@("`@(&5L<V4Z"B`@("`@("`@("`@(&5X
M:71P9VTH*0H*("`@(",@<V%M90H@("`@9&5F(&%R9W,H<V5L9BP@82DZ"B`@
M("`@("`@:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=A<F<M;&ES
M="<I.@H@("`@("`@("`@("!R971U<FX@<V5L9BYA<F=?;&ES="AA*0H@("`@
M("`@(&5L:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9O;&QO=R@G87)G+6QI
M<W0G*3H*("`@("`@("`@("`@<F5T=7)N(&$*("`@("`@("!E;'-E.@H@("`@
M("`@("`@("!E>&ET<&=M*"D*"B`@("!D968@87)G7VQI<W0H<V5L9BP@82DZ
M"B`@("`@("`@:68@<V5L9BYN="AA*2!I;B!S96QF+F=E=&9I<G-T*"=A<F<M
M;&ES="<I.@H@("`@("`@("`@("!B(#T@<V5L9BYE>'!R<VXH82D*("`@("`@
M("`@("`@<F5T=7)N('-E;&8N3RAB*0H@("`@("`@(&5L<V4Z"B`@("`@("`@
M("`@(&5X:71P9VTH*0H*("`@(&1E9B!/*'-E;&8L(&$I.@H@("`@("`@(&EF
M('-E;&8N;G0H82D@:6X@6R<L)UTZ"B`@("`@("`@("`@(&(@/2!S96QF+F%C
M8V5P="@G+"<L(&$I"B`@("`@("`@("`@(&,@/2!S96QF+F5X<')S;BAB*0H@
M("`@("`@("`@("!D(#T@<V5L9BY/*&,I"B`@("`@("`@("`@(')E='5R;B!D
M"B`@("`@("`@96QI9B!S96QF+FYT*&$I(&EN('-E;&8N9V5T9F]L;&]W*"=/
M)RDZ"B`@("`@("`@("`@(')E='5R;B!A"B`@("`@("`@96QS93H*("`@("`@
/("`@("`@97AI='!G;2@I
`
end
SHAR_EOF
  (set 20 16 11 11 22 14 54 'parse.py'; eval "$shar_touch") &&
  chmod 0644 'parse.py'
if test $? -ne 0
then ${echo} 'restore of parse.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'parse.py: MD5 check failed'
       ) << \SHAR_EOF
454f0e06c9afb62b22062af9182f383d  parse.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'parse.py'` -ne 17250 && \
  ${echo} 'restoration warning:  size of parse.py is not 17250'
  fi
fi
# ============= Proj3.py ==============
if test -f 'Proj3.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING Proj3.py (file already exists)'
else
${echo} 'x - extracting Proj3.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 Proj3.py
M:6UP;W)T('-Y<PT*:6UP;W)T(%-E;6%N=&EC<PT*:6UP;W)T(&QE>&EC86P-
M"FEM<&]R="!Q=65U90T*:6UP;W)T(&9I;F1C;6YT<PT*#0H-"FEF(%]?;F%M
M95]?(#T]("=?7VUA:6Y?7R<Z#0H@("`@;&EN97,@/2!;70T*("`@(&0@/2![
M?0T*("`@('$@/2!Q=65U92Y1=65U92@I#0H@("`@=')Y.@T*("`@("`@("!W
M:71H(&]P96XH<WES+F%R9W9;,5TL("=R)RD@87,@9FEL93H-"B`@("`@("`@
M("`@('!A<W,-"B`@("`@("`@("`@(&9O<B!E(&EN(&9I;&4Z#0H@("`@("`@
M("`@("`@("`@;&EN97,N87!P96YD*&4N<G-T<FEP*"=<;B<I*0T*("`@("`@
M("`@("`@9FEL92YC;&]S92@I#0H@("`@97AC97!T.@T*("`@("`@("!P<FEN
M="`G5&AI<R!P<F]G<F%M(&YE961S(&$@9FEL92!A<F=U;65N="XG#0H@("`@
M:68@;&EN97,Z#0H@("`@("`@(&9O<B!L:6YE(&EN(&QI;F5S.@T*("`@("`@
M("`@("`@:68@;&5N*&QI;F4I(#X@,#H-"B`@("`@("`@("`@("`@("!P<FEN
M="!L:6YE#0H@("`@("`@("`@("`@("`@;&EN92`](&9I;F1C;6YT<RYF:6YD
M8VUN=',H;&EN92D-"B`@("`@("`@("`@("`@("!Q+"!E(#T@;&5X:6-A;"YL
M97AI8V%L*&QI;F4L('$L(&0I#0H@("`@("`@("`@("`@("`@9"YU<&1A=&4H
M92D-"B`@("`@("`@:68@;F]T('$N:7-%;7!T>2@I(&%N9"!D.@T*("`@("`@
M("`@("`@<2YE;G%U975E*"<D)RD-"B`@("`@("`@("`@(&0N=7!D871E*'LG
M)"<Z("<D)WTI#0H@("`@("`@("`@("!N(#TP#0H@("`@("`@("`@("!F;W(@
M;&EN92!I;B!L:6YE<SH-"B`@("`@("`@("`@("`@("!N;#UL:6YE+G-P;&ET
M*"D-"B`@("`@("`@("`@("`@("!I9B`G:6YT)R!N;W0@:6X@;FPZ#0H@("`@
M("`@("`@("`@("`@("`@(&EF("=F;&]A="<@;F]T(&EN(&YL.@T*("`@("`@
M("`@("`@("`@("`@("`@("`@8G)E86L-"B`@("`@("`@("`@("`@("!N*STQ
M#0H@("`@("`@("`@("!N<2`]('%U975E+E%U975E*"D-"B`@("`@("`@("`@
M(&YD(#U[?0T*("`@("`@("`@("`@;G$L(&YD(#T@;&5X:6-A;"YL97AI8V%L
M*&QI;F5S6VXZ75LP72QN<2QN9"D-"B`@("`@("`@("`@(',@/2!396UA;G1I
M8W,N<V5M86YT:6-S*&YQ+&0L;&EN97-;;CI=*0T*("`@("`@("`@("`@:68@
M<RYS=&%R="@I.@T*("`@("`@("`@("`@("`@('!R:6YT)T%#0T505"<-"B`@
M("`@("`@("`@(&5L<V4Z#0H@("`@("`@("`@("`@("`@<')I;G0@)U)%2D5#
$5"<-"B`@
`
end
SHAR_EOF
  (set 20 16 11 07 14 45 30 'Proj3.py'; eval "$shar_touch") &&
  chmod 0644 'Proj3.py'
if test $? -ne 0
then ${echo} 'restore of Proj3.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'Proj3.py: MD5 check failed'
       ) << \SHAR_EOF
fbacb026d96fc545f0d9f422fbf9ade9  Proj3.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'Proj3.py'` -ne 1219 && \
  ${echo} 'restoration warning:  size of Proj3.py is not 1219'
  fi
fi
# ============= queue.py ==============
if test -f 'queue.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING queue.py (file already exists)'
else
${echo} 'x - extracting queue.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 queue.py
M8VQA<W,@475E=64H;V)J96-T*3H*"B`@("!D968@7U]I;FET7U\H<V5L9BDZ
M"B`@("`@("`@<V5L9BYI=&5M<R`](%M="B`@("`@("`@<V5L9BYI(#T@;&5N
M*'-E;&8N:71E;7,I"@H@("`@9&5F(&ES16UP='DH<V5L9BDZ"B`@("`@("`@
M<F5T=7)N('-E;&8N:71E;7,@/3T@6UT*"B`@("!D968@96YQ=65U92AS96QF
M+"!I=&5M*3H*("`@("`@("!S96QF+FET96US+FEN<V5R="@P+"!I=&5M*0H@
M("`@("`@('-E;&8N:2`K/2`Q"@H@("`@9&5F(&1E<75E=64H<V5L9BDZ"B`@
M("`@("`@<V5L9BYI("T](#$*("`@("`@("!R971U<FX@<V5L9BYI=&5M<RYP
M;W`H*0H*("`@(&1E9B!S:7IE*'-E;&8I.@H@("`@("`@(')E='5R;B!L96XH
M<V5L9BYI=&5M<RD*"B`@("!D968@<')I;G1Q*'-E;&8I.@H@("`@("`@('!R
M:6YT('-E;&8N:71E;7,*"B`@("!D968@<69R;VYT*'-E;&8I.@H@("`@("`@
M(')E='5R;B!S96QF+FET96US6VQE;BAS96QF+FET96US*2TQ70H*("`@(&1E
M9B!C=7)R96YT=&]K96XH<V5L9BDZ"B`@("`@("`@:68@,"`\('-E;&8N:2`\
M/2!L96XH<V5L9BYI=&5M<RDZ"B`@("`@("`@("`@(')E='5R;B!S96QF+FET
M96US6W-E;&8N:2TQ70H*("`@(&1E9B!A8V-E<'0H<V5L9BDZ"B`@("`@("`@
M<V5L9BYI("T](#$*"B`@("!D968@:6YD97AE9"AS96QF+"!N*3H*("`@("`@
M("!I9B`P(#P@;B`\/2!L96XH<V5L9BYI=&5M<RDZ"B`@("`@("`@("`@(')E
4='5R;B!S96QF+FET96US6VXM,5UL
`
end
SHAR_EOF
  (set 20 16 11 11 20 03 48 'queue.py'; eval "$shar_touch") &&
  chmod 0644 'queue.py'
if test $? -ne 0
then ${echo} 'restore of queue.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'queue.py: MD5 check failed'
       ) << \SHAR_EOF
ae3697fe4e758617671da81126436192  queue.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'queue.py'` -ne 740 && \
  ${echo} 'restoration warning:  size of queue.py is not 740'
  fi
fi
# ============= sample.txt ==============
if test -f 'sample.txt' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING sample.txt (file already exists)'
else
${echo} 'x - extracting sample.txt (text)'
  sed 's/^X//' << 'SHAR_EOF' > 'sample.txt' &&
ACCEPT
SHAR_EOF
  (set 20 16 11 11 22 21 00 'sample.txt'; eval "$shar_touch") &&
  chmod 0644 'sample.txt'
if test $? -ne 0
then ${echo} 'restore of sample.txt failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'sample.txt: MD5 check failed'
       ) << \SHAR_EOF
50fcb8692d9dfb377a6526899e8916ac  sample.txt
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'sample.txt'` -ne 7 && \
  ${echo} 'restoration warning:  size of sample.txt is not 7'
  fi
fi
# ============= Semantics.py ==============
if test -f 'Semantics.py' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING Semantics.py (file already exists)'
else
${echo} 'x - extracting Semantics.py (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 Semantics.py
M:6UP;W)T(&9I;F1C;6YT<PII;7!O<G0@;&5X:6-A;`II;7!O<G0@<75E=64*
M"@IC;&%S<R!S96UA;G1I8W,H;V)J96-T*3H*("`@(&1E9B!?7VEN:71?7RAS
M96QF+"!Q+"!D+"!S>6TL(&QI;F5S*3H*("`@("`@("!S96QF+G$@/2!Q"B`@
M("`@("`@<V5L9BYD(#T@9`H@("`@("`@('-E;&8N<WEM(#T@<WEM"B`@("`@
M("`@<V5L9BYL:6YE<R`](&QI;F5S"@H@("`@9&5F(&%C8V5P="AS96QF+"!S
M+"!A*3H*("`@("`@("!I9B!S96QF+FYT*&$I(&EN(',Z"B`@("`@("`@("`@
M('!R:6YT)V%C8V5P=&5D.B<L('-E;&8N;G0H82D*("`@("`@("`@("`@<F5T
M=7)N(&$@+2`Q"@H@("`@9&5F('-T87)T*'-E;&8I.@H@("`@("`@(&-H:R`]
M(%M="B`@("`@("`@8VAK+F%P<&5N9"AS96QF+FUA:6YC:&LH*2D*("`@("`@
M("`C(&-H:RYA<'!E;F0H<V5L9BYR971U<FYC:&LH*2D*("`@("`@("!C:&LN
M87!P96YD*'-E;&8N8VAK<F5T=7)N*0H@("`@("`@(",@:70@=VEL;"!C86QL
M(&%L;"!T:&4@<V5M86YT:6,@8VAE8VL@;65T:&]D<PH@("`@("`@(",@:70@
M=VEL;"!S=&]R92!A;&P@<F5T=7)N('9A;'5E<R!I;B!A(&QI<W0*("`@("`@
M("`C(&%T('1H92!E;F0@:70@=VEL;"!C:&5C:R!I="!&86QS92!I<R!I;B!T
M:&4@;&ES=`H@("`@("`@(",@:68@>65S+"!R971U<FX@1F%L<V4L(&5L<V4@
M<F5T=7)N(%1R=64*("`@("`@("!I9B!&86QS92!I;B!C:&LZ"B`@("`@("`@
M("`@(')E='5R;B!&86QS90H@("`@("`@(&5L<V4Z"B`@("`@("`@("`@(')E
M='5R;B!4<G5E"@H@("`@9&5F(&YT*'-E;&8I.@H@("`@("`@(')E='5R;B!S
M96QF+G$N8W5R<F5N='1O:V5N*"D*"B`@("!D968@;6%I;F-H:RAS96QF*3H*
M("`@("`@("!N(#T@,`H@("`@("`@(&9O<B!L:6YE(&EN('-E;&8N;&EN97,Z
M"B`@("`@("`@("`@(&EF("=V;VED(&UA:6X@*"!V;VED("DG(&EN(&QI;F4Z
M"B`@("`@("`@("`@("`@("!B<F5A:PH@("`@("`@("`@("!N("L](#$*("`@
M("`@("`@("`@:68@;B`]/2!L96XH<V5L9BYL:6YE<RDZ"B`@("`@("`@("`@
M("`@("!R971U<FX@1F%L<V4*("`@("`@("!F;W(@;&EN92!I;B!S96QF+FQI
M;F5S6VXZ73H*("`@("`@("`@("`@:68@)WLG(&EN(&QI;F4Z"B`@("`@("`@
M("`@("`@("!B<F5A:PH@("`@("`@("`@("!N("L](#$*("`@("`@("!F;W(@
M;&EN92!I;B!S96QF+FQI;F5S6VXZ73H*("`@("`@("`@("`@:68@)WTG(&EN
M(&QI;F4Z"B`@("`@("`@("`@("`@("!B<F5A:PH@("`@("`@("`@("!N("L]
M(#$*("`@("`@("!I9B!N("L@,2`]/2!L96XH<V5L9BYL:6YE<RDZ"B`@("`@
M("`@("`@(')E='5R;B!&86QS90H@("`@("`@(')E='5R;B!4<G5E"@H@("`@
M9&5F(')E='5R;F-H:RAS96QF*3H*("`@("`@("!N(#T@,`H@("`@("`@(&9O
M<B!L:6YE(&EN('-E;&8N;&EN97,Z"B`@("`@("`@("`@(&QI;F4@/2!F:6YD
M8VUN=',N9FEN9&-M;G1S*&QI;F4I"B`@("`@("`@("`@(&YL(#T@;&EN92YS
M<&QI="@I"B`@("`@("`@("`@(&EF(&YL.@H@("`@("`@("`@("`@("`@:68@
M)W9O:60G(&YO="!I;B!N;"!A;F0@)VEN="<@;F]T(&EN(&YL(&%N9"`G9FQO
M870G(&YO="!I;B!N;"!A;F0@)WLG(&YO="!I;B!N;#H*("`@("`@("`@("`@
M("`@("`@("!B<F5A:PH@("`@("`@("`@("!N("L](#$*("`@("`@("!N<2`]
M('%U975E+E%U975E*"D*("`@("`@("!N9"`]('M]"B`@("`@("`@9F]R(&QI
M;F4@:6X@<V5L9BYL:6YE<UMN.ETZ"B`@("`@("`@("`@(&EF(&QI;F4Z"B`@
M("`@("`@("`@("`@("!N<2P@;F0L('-Y;3(L('1R=60@/2!L97AI8V%L+FQE
M>&EC86PH;&EN92P@;G$L(&YD*0H@("`@("`@(&X@/2!S96QF+G$N<VEZ92@I
M"B`@("`@("`@=&L@/2!S96QF+FYT*"D*("`@("`@("!W:&EL92!T:R`A/2`G
M<F5T=7)N)R!A;F0@=&L@(3T@)WTG.@H@("`@("`@("`@("!N("T](#$*("`@
M("`@("`@("`@=&L@/2!S96QF+G$N:6YD97AE9"AN*0H@("`@("`@(&EF('1K
M(#T]("=])SH*("`@("`@("`@("`@<F5T=7)N(%1R=64*("`@("`@("!E;&EF
M('1K(#T]("=R971U<FXG.@H@("`@("`@("`@("!N("T](#$*("`@("`@("`@
M("`@:68@<V5L9BYQ+FEN9&5X960H;BD@/3T@)SLG.@H@("`@("`@("`@("`@
M("`@;B`M/2`Q"B`@("`@("`@("`@("`@("!W:&EL92!S96QF+G$N:6YD97AE
M9"AN*2`A/2`G?2<Z"B`@("`@("`@("`@("`@("`@("`@;B`M/2`Q"B`@("`@
M("`@("`@("`@("!R971U<FX@<V5L9BYQ+FEN9&5X960H;BD@/3T@)WTG"B`@
M("`@("`@("`@(&5L<V4Z"B`@("`@("`@("`@("`@("!R971U<FX@1F%L<V4*
M("`@("`@("!E;'-E.@H@("`@("`@("`@("!R971U<FX@1F%L<V4*"B`@("!D
M968@:7-F=6XH<V5L9BP@<RDZ"B`@("`@("`@:68@<R!I;B!S96QF+G-Y;2YK
M97ES*"DZ"B`@("`@("`@("`@(&EF('-E;&8N<WEM6W-=(#T]("=V;VED)SH*
M("`@("`@("`@("`@("`@(')E='5R;B!4<G5E"B`@("`@("`@("`@(&X@/2!S
M96QF+G$N<VEZ92@I"B`@("`@("`@("`@('=H:6QE(&X@/B`Q.@H@("`@("`@
M("`@("`@("`@:68@<V5L9BYQ+FEN9&5X960H;BD@/3T@<R!A;F0@<V5L9BYQ
M+FEN9&5X960H;B`M(#$I(#T]("<H)SH*("`@("`@("`@("`@("`@("`@("!R
M971U<FX@5')U90H@("`@("`@("`@("`@("`@;B`M/2`Q"B`@("`@("`@<F5T
M=7)N($9A;'-E"@H@("`@9&5F(&-H:W)E='5R;BAS96QF*3H*("`@("`@("!N
M(#T@<V5L9BYQ+G-I>F4H*0H@("`@("`@('=H:6QE(&X@/B`Q.@H@("`@("`@
M("`@("!I9B!S96QF+G$N:6YD97AE9"AN*2!I;B!S96QF+G-Y;2YK97ES*"DZ
M"B`@("`@("`@("`@("`@("!I9B!S96QF+FES9G5N*'-E;&8N<2YI;F1E>&5D
M*&XI*3H*("`@("`@("`@("`@("`@("`@("!F=6X@/2!S96QF+G$N:6YD97AE
M9"AN*0H@("`@("`@("`@("`@("`@("`@('=H:6QE('-E;&8N<2YI;F1E>&5D
M*&XI("$]("=R971U<FXG(&%N9"!S96QF+G$N:6YD97AE9"AN*2`A/2`G?2<Z
M"B`@("`@("`@("`@("`@("`@("`@("`@(&X@+3T@,0H@("`@("`@("`@("`@
M("`@("`@(&EF('-E;&8N<WEM6V9U;ET@/3T@)W9O:60G(&%N9"!S96QF+G$N
M:6YD97AE9"AN*2`]/2`G?2<Z"B`@("`@("`@("`@("`@("`@("`@("`@(&EF
M(&X@/3T@,3H*("`@("`@("`@("`@("`@("`@("`@("`@("`@(')E='5R;B!4
M<G5E"B`@("`@("`@("`@("`@("`@("`@("`@(&5L<V4Z"B`@("`@("`@("`@
M("`@("`@("`@("`@("`@("!N+3TQ"B`@("`@("`@("`@("`@("`@("`@("`@
M("`@("!C;VYT:6YU90H@("`@("`@("`@("`@("`@("`@(&5L:68@<V5L9BYS
M>6U;9G5N72`]/2`G=F]I9"<@86YD('-E;&8N<2YI;F1E>&5D*&XI(#T]("=R
M971U<FXG.@H@("`@("`@("`@("`@("`@("`@("`@("!N("T](#$*("`@("`@
M("`@("`@("`@("`@("`@("`@:68@<V5L9BYQ+FEN9&5X960H;BD@/3T@)SLG
M.@H@("`@("`@("`@("`@("`@("`@("`@("`@("`@=VAI;&4@<V5L9BYQ+FEN
M9&5X960H;BD@(3T@)WTG.@H@("`@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@(&XM/3$*("`@("`@("`@("`@("`@("`@("`@("`@("`@(&EF(&X@/3T@
M,3H*("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("!R971U<FX@5')U
M90H@("`@("`@("`@("`@("`@("`@("`@("`@("`@96QS93H*("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("!N+3TQ"B`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@8V]N=&EN=64*("`@("`@("`@("`@("`@("`@("!E
M;&EF('-E;&8N<2YI;F1E>&5D*&XI(#T]("=R971U<FXG.@H@("`@("`@("`@
M("`@("`@("`@("`@("!N+3TQ"B`@("`@("`@("`@("`@("`@("`@("`@('1E
M;7`]6UT*("`@("`@("`@("`@("`@("`@("`@("`@=VAI;&4@<V5L9BYQ+FEN
M9&5X960H;BD@(3T@)SLG.@H@("`@("`@("`@("`@("`@("`@("`@("`@("`@
M=&5M<"YA<'!E;F0H<V5L9BYQ+FEN9&5X960H;BDI"B`@("`@("`@("`@("`@
M("`@("`@("`@("`@("!N+3TQ"B`@("`@("`@("`@("`@("`@("`@("`@(&9R
M;VT@9C,@:6UP;W)T('1R=60*("`@("`@("`@("`@("`@("`@("`@("`@:68@
M;&5N*'1E;7`I(#T],3H*("`@("`@("`@("`@("`@("`@("`@("`@("`@(&EF
M('1R=61;<V5L9BYQ+FEN9&5X960H;B`M(#$I72`]/2!S96QF+G-Y;5MF=6Y=
M.@H@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@('=H:6QE('-E;&8N
M<2YI;F1E>&5D*&XI("$]("=])R!A;F0@;CXQ.@H@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("!N("T](#$*("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("!I9B!N(#T](#$Z"B`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@(')E='5R;B!4<G5E"B`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@96QS93H*("`@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@;B`M/2`Q"B`@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@(&-O;G1I;G5E"B`@("`@("`@("`@("`@("`@("`@("`@("`@
M("!E;'-E.@H@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@(')E='5R
M;B!&86QS90H@("`@("`@("`@("`@("`@("`@("`@("!E;'-E.@H@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@9F]R(&D@:6X@=&5M<#H*("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("!I9B!I(&EN('-E;&8N<WEM+FME>7,H
M*2`K(%LG6R<L("==)RP@)R@G+"`G*2<L("<E)RP@)RLG+"`G+2<L("<J)RP@
M)R\G73H*("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@:68@
M:2!I;B!S96QF+G-Y;2YK97ES*"DZ"B`@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("!I9B!T<G5D6VE=(#T]('-E;&8N<WEM6V9U;ETZ
M"B`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@
M:68@:2$]=&5M<%ML96XH=&5M<"DM,5TZ"B`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@(&-O;G1I;G5E"B`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@=VAI;&4@<V5L
M9BYQ+FEN9&5X960H;BD@(3T@)WTG(&%N9"!N(#X@,3H*("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@;B`M/2`Q"B`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@:68@
M;B`]/2`Q.@H@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("!R971U<FX@5')U90H@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@(&5L<V4Z"B`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@(&X@+3T@,0H@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("!C;VYT
M:6YU90H@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("!E;'-E
M.@H@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@<F5T
M=7)N($9A;'-E"B`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@96QS
M93H*("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@<F5T=7)N
9($9A;'-E"B`@("`@("`@("`@(&X@+3T@,2`@
`
end
SHAR_EOF
  (set 20 16 11 11 22 02 03 'Semantics.py'; eval "$shar_touch") &&
  chmod 0644 'Semantics.py'
if test $? -ne 0
then ${echo} 'restore of Semantics.py failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'Semantics.py: MD5 check failed'
       ) << \SHAR_EOF
9f3df3cf0f0284648814e4abfc92726c  Semantics.py
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'Semantics.py'` -ne 5605 && \
  ${echo} 'restoration warning:  size of Semantics.py is not 5605'
  fi
fi
# ============= test1.txt ==============
if test -f 'test1.txt' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING test1.txt (file already exists)'
else
${echo} 'x - extracting test1.txt (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 test1.txt
M#0HO*B!T97-T(&9O<B!B87-I8R!F=6YT:6]N86QI='D@;V8@<')O:B`S("T@
M<VAO=6QD('!A<W,@*B\-"B\J('1E<W0@,2`J+PT*#0IV;VED(&UA:6X@*"!V
H;VED("D-"GL-"@EI;G0@>CL-"@D-"@EZ(#T@,B\U.PT*#0I]#0H-"FX@
`
end
SHAR_EOF
  (set 20 16 11 07 14 40 40 'test1.txt'; eval "$shar_touch") &&
  chmod 0644 'test1.txt'
if test $? -ne 0
then ${echo} 'restore of test1.txt failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'test1.txt: MD5 check failed'
       ) << \SHAR_EOF
c30337e383a3ba20ef3251945c6e9676  test1.txt
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'test1.txt'` -ne 130 && \
  ${echo} 'restoration warning:  size of test1.txt is not 130'
  fi
fi
# ============= test.txt ==============
if test -f 'test.txt' && test "$first_param" != -c; then
  ${echo} 'x -SKIPPING test.txt (file already exists)'
else
${echo} 'x - extracting test.txt (binary)'
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 test.txt
M=F]I9"!F=6YC*'9O:60I#0I[#0H@("`@<F5T=7)N(#L-"GT-"G9O:60@;6%I
M;BAV;VED*0T*>PT*("`@:6YT('@[#0H@("!W:&EL92AX/#$I('L-"B`@("`@
I('@]>"LU.PT*("`@?0T*("`@9G5N8R@I.PT*("`@<F5T=7)N(#L-"GT@
`
end
SHAR_EOF
  (set 20 16 11 11 22 14 12 'test.txt'; eval "$shar_touch") &&
  chmod 0644 'test.txt'
if test $? -ne 0
then ${echo} 'restore of test.txt failed'
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'test.txt: MD5 check failed'
       ) << \SHAR_EOF
9c87f41405ba561a754f7703facc2c61  test.txt
SHAR_EOF
  else
test `LC_ALL=C wc -c < 'test.txt'` -ne 131 && \
  ${echo} 'restoration warning:  size of test.txt is not 131'
  fi
fi
if rm -fr ${lock_dir}
then ${echo} 'x - removed lock directory `'${lock_dir}\''.'
else ${echo} 'x - failed to remove lock directory `'${lock_dir}\''.'
  exit 1
fi
exit 0
